export const FLOW_TYPES=['Expense','Income','Transfer','Investment','Ignore']
const TRANSFER_CATEGORIES=new Set(['Credit Card Payment','Internal Transfers'])
export function importedFlow(transaction){if(transaction.isIncome||transaction.rawCategory==='Income')return'Income';if(transaction.rawCategory==='Investment'||transaction.bucket==='Investments')return'Investment';if(TRANSFER_CATEGORIES.has(transaction.rawCategory))return'Transfer';return'Expense'}
export function effectiveTransaction(transaction){const flow=transaction.flow||transaction.overrideFlow||transaction.importedFlow||importedFlow(transaction),bucket=transaction.bucket||transaction.overrideBucket||transaction.originalBucket||transaction.rawCategory||'Uncategorized';return{...transaction,bucket,flow,isIncome:flow==='Income'}}
export function trueSpending(rows){return rows.filter(row=>!row.deletedAt&&!row.matchedTxnKey).map(effectiveTransaction).filter(row=>row.flow==='Expense')}
export function monthEndDate(monthKey){if(!/^\d{4}-\d{2}$/.test(monthKey||''))return null;const [year,month]=monthKey.split('-').map(Number),day=new Date(year,month,0).getDate();return `${monthKey}-${String(day).padStart(2,'0')}`}
export function monthlySummary(rows){
  const active=rows.filter(row=>!row.deletedAt&&!row.matchedTxnKey),effective=active.map(effectiveTransaction),spending=effective.filter(row=>row.flow==='Expense'),income=effective.filter(row=>row.flow==='Income').reduce((sum,row)=>sum+Math.max(0,-Number(row.amount)||0),0),byCategory={},highestByCategory={}
  for(const row of spending){byCategory[row.bucket]=(byCategory[row.bucket]||0)+row.amount;if(row.amount>0&&(!highestByCategory[row.bucket]||row.amount>highestByCategory[row.bucket].amount))highestByCategory[row.bucket]=row}
  const totalSpent=spending.reduce((sum,row)=>sum+row.amount,0),topExpenses=spending.filter(row=>row.amount>0&&row.bucket!=='Fixed Expenses'&&row.rawCategory!=='Loan Payment').sort((a,b)=>b.amount-a.amount).slice(0,5),topCategories=Object.entries(byCategory).map(([bucket,amount])=>({bucket,amount,highestExpense:highestByCategory[bucket]||null})).sort((a,b)=>b.amount-a.amount).slice(0,5),dates=active.filter(row=>row.source!=='manual').map(row=>String(row.date||'')).filter(date=>/^\d{4}-\d{2}-\d{2}$/.test(date)).sort(),coverageThrough=dates.at(-1)||null,monthKey=coverageThrough?.slice(0,7)||null,monthEnd=monthEndDate(monthKey)
  return{totalSpent,totalIncome:income,netProfit:income-totalSpent,topExpenses,topCategories,byCategory,coverageThrough,monthEnd,fullMonthData:Boolean(coverageThrough&&coverageThrough===monthEnd)}
}
export function budgetsByMonth(rows){return rows.reduce((result,row)=>{(result[row.monthKey]||={})[row.bucket]={target:Number(row.target),paced:row.paced,sortOrder:Number(row.sortOrder)||0};return result},{})}
export function budgetLimitsByMonth(rows){return rows.reduce((result,row)=>{result[row.monthKey]=Number(row.spendingLimit)||0;return result},{})}
