import test from 'node:test'
import assert from 'node:assert/strict'
import { budgetRingData,cutbackOpportunities,latestTransactionMonth,monthlyMood } from '../src/lib/monthlyHome.js'
import { onRequestPost as completeReview } from '../functions/api/review.js'

test('latest upload month comes from the newest valid transaction date',()=>{assert.equal(latestTransactionMonth([{date:'2026-01-03'},{date:'bad'},{date:'2026-08-01'},{date:'2026-07-31'}]),'2026-08');assert.equal(latestTransactionMonth([]),null)})
test('budget and spending rings reconcile to category totals',()=>{const result=budgetRingData({pacing:[{bucket:'Dining',target:200},{bucket:'Travel',target:300},{bucket:'Unused',target:0}],byCategory:{Dining:125,Travel:50,Other:25,Refund:-10}});assert.equal(result.budget.reduce((sum,row)=>sum+row.value,0),500);assert.equal(result.actual.reduce((sum,row)=>sum+row.value,0),200);assert.deepEqual(result.names,['Dining','Travel','Other'])})
test('month mood stays neutral while open and judges only closed months',()=>{const base={budgetTotal:500,transactionCount:10,remaining:100,projectedTotal:450,currentMonth:'2026-09'};assert.equal(monthlyMood({...base,month:'2026-09'}).state,'progress');assert.equal(monthlyMood({...base,month:'2026-08'}).state,'under');assert.equal(monthlyMood({...base,month:'2026-08',remaining:-1}).state,'over');assert.equal(monthlyMood({...base,month:'2026-08',budgetTotal:0}).state,'no-budget');assert.equal(monthlyMood({...base,month:'2026-08',transactionCount:0}).state,'no-data')})
test('cutback opportunities use the prior month, exclude fixed expenses, and compare covered history',()=>{const rows=[{date:'2026-06-05',amount:100,bucket:'Dining',flow:'Expense'},{date:'2026-07-05',amount:200,bucket:'Dining',flow:'Expense'},{date:'2026-08-05',amount:300,bucket:'Dining',flow:'Expense'},{date:'2026-08-01',amount:4000,bucket:'Fixed Expenses',flow:'Expense'}],coverage=[{from:'2026-06-01',through:'2026-08-31'}],result=cutbackOpportunities(rows,[{monthKey:'2026-08',bucket:'Dining',target:225}],coverage,'2026-09');assert.equal(result.complete,true);assert.equal(result.rows.length,1);assert.equal(result.rows[0].bucket,'Dining');assert.equal(result.rows[0].average,200);assert.equal(result.rows[0].difference,100);assert.equal(result.rows[0].target,225)})
test('review completion is tied to the current upload event',async()=>{const env={DB:{prepare:sql=>({bind:(...values)=>({first:async()=>null,run:async()=>({meta:{changes:sql.startsWith('UPDATE')&&values[3]===17?1:0}})})})}},requestFor=id=>new Request('https://example.test/api/review',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({monthKey:'2026-08',uploadEventId:id,revision:0})});const ok=await completeReview({request:requestFor(17),env}),stale=await completeReview({request:requestFor(16),env});assert.equal(ok.status,200);assert.equal(stale.status,409)})
