import test from 'node:test'
import assert from 'node:assert/strict'
import { buildPortfolio, localDateKey } from '../src/lib/portfolio.js'
import { importedFlow, monthlySummary } from '../src/lib/tracker.js'
const row=(date,amount,bucket,flow='Expense',name=bucket)=>({date,amount,name,rawCategory:bucket,originalBucket:bucket,bucket,flow,account:'Checking'})
test('local date keys do not shift local midnight',()=>assert.equal(localDateKey(new Date(2026,2,1)),'2026-03-01'))
test('classifies imported non-spending flows while retaining loan payments as true expenses',()=>{assert.equal(importedFlow({...row('2026-03-01',100,'Investments'),'rawCategory':'Investment'}),'Investment');assert.equal(importedFlow({...row('2026-03-01',100,'Fixed Expenses'),'rawCategory':'Credit Card Payment'}),'Transfer');assert.equal(importedFlow({...row('2026-03-01',100,'Fixed Expenses'),'rawCategory':'Loan Payment'}),'Expense')})
test('top expenses and categories include only effective expense flows',()=>{const market=row('2026-03-01',50,'Groceries','Expense','Market'),s=monthlySummary([market,row('2026-03-02',25,'Groceries','Expense','Shop'),row('2026-03-03',500,'Bills','Transfer','Payment'),row('2026-03-04',100,'Dining','Ignore','Cafe')]);assert.equal(s.totalSpent,75);assert.equal(s.topExpenses[0].name,'Market');assert.equal(s.topCategories[0].bucket,'Groceries');assert.equal(s.topCategories[0].amount,75);assert.equal(s.topCategories[0].highestExpense.name,'Market')})
test('loan payments remain in totals but are omitted from top individual expenses',()=>{const mortgage={...row('2026-03-01',4000,'Fixed Expenses','Expense','Mortgage'),rawCategory:'Loan Payment'},groceries=row('2026-03-02',200,'Groceries','Expense','Market'),s=monthlySummary([mortgage,groceries]);assert.equal(s.totalSpent,4200);assert.equal(s.topExpenses[0].name,'Market');assert.equal(s.topCategories[0].bucket,'Fixed Expenses')})
test('uses monthly budgets, prorates current month, and leaves lumpy categories unprojected',()=>{const p=buildPortfolio({'2026-03':[row('2026-03-01',200,'Groceries'),row('2026-03-01',400,'Bills')]},{'2026-03':{Groceries:{target:620,paced:true},Bills:{target:400,paced:false}}},new Date(2026,2,10));const g=p.monthly['2026-03'].pacing.find(x=>x.bucket==='Groceries'),b=p.monthly['2026-03'].pacing.find(x=>x.bucket==='Bills');assert.equal(g.proratedTarget,200);assert.equal(g.paceRatio,1);assert.equal(b.projected,null)})
test('category and flow overrides drive summaries',()=>{const s=monthlySummary([{...row('2026-03-01',90,'Shopping'),originalBucket:'Shopping',bucket:'Groceries',importedFlow:'Expense',flow:'Expense',overrideBucket:'Groceries'},{...row('2026-03-02',50,'Dining'),flow:'Ignore',overrideFlow:'Ignore'}]);assert.equal(s.topCategories[0].bucket,'Groceries');assert.equal(s.topCategories[0].amount,90);assert.equal(s.topCategories[0].highestExpense.bucket,'Groceries')})
