import { useEffect,useMemo,useState } from 'react'
import { Cell,Pie,PieChart,ResponsiveContainer,Tooltip } from 'recharts'
import { formatCurrency,PALETTE } from '../lib/finance.js'
import { postJson } from '../lib/sharedState.js'
import { budgetMoney as money,budgetSnapshot as snapshot,priorActualPlan as priorPlan,reorderBudgetItems } from '../lib/budgetBuilder.js'
import IconButton from './IconButton.jsx'

export default function BudgetEditor({month,current,previous,categories,setting,onChanged,onDirtyChange}){
  const savedItems=useMemo(()=>(current?.pacing||[]).map(({bucket,target,paced})=>({bucket,target,paced})),[current?.pacing])
  const hasSaved=Boolean(setting)||savedItems.length>0
  const initialItems=useMemo(()=>hasSaved?savedItems:priorPlan(previous),[hasSaved,savedItems,previous])
  const persisted=useMemo(()=>hasSaved?snapshot(savedItems.reduce((sum,row)=>sum+money(row.target),0),savedItems):snapshot(0,[]),[hasSaved,savedItems])
  const [items,setItems]=useState(initialItems),[baseline,setBaseline]=useState(persisted),[dragging,setDragging]=useState(''),[saving,setSaving]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('')
  useEffect(()=>{setItems(initialItems);setBaseline(persisted)},[month,initialItems,persisted])
  useEffect(()=>{setNotice('');setError('')},[month])

  const priorActual=previous?.byCategory||{},currentActual=current?.byCategory||{},planned=new Set(items.map(item=>item.bucket))
  const bank=categories.filter(bucket=>!planned.has(bucket)).sort((a,b)=>(priorActual[b]||0)-(priorActual[a]||0)||a.localeCompare(b))
  const allocated=items.reduce((sum,item)=>sum+money(item.target),0)
  const dirty=snapshot(allocated,items)!==baseline
  const pieData=items.filter(item=>money(item.target)>0).map(item=>({name:item.bucket,value:money(item.target)}))
  if(!pieData.length)pieData.push({name:'No category budgets',value:1,empty:true})
  useEffect(()=>{onDirtyChange?.(dirty)},[dirty,onDirtyChange])
  useEffect(()=>{const warn=event=>{if(!dirty)return;event.preventDefault();event.returnValue=''};addEventListener('beforeunload',warn);return()=>removeEventListener('beforeunload',warn)},[dirty])

  const add=bucket=>{if(!bucket||planned.has(bucket))return;setItems(rows=>[...rows,{bucket,target:Number((priorActual[bucket]||0).toFixed(2)),paced:true}]);setNotice('')}
  const remove=bucket=>setItems(rows=>rows.filter(row=>row.bucket!==bucket))
  const update=(bucket,patch)=>setItems(rows=>rows.map(row=>row.bucket===bucket?{...row,...patch}:row))
  const move=(index,direction)=>setItems(rows=>{const next=[...rows],target=index+direction;if(target<0||target>=next.length)return rows;[next[index],next[target]]=[next[target],next[index]];return next})
  const reorder=(bucket,before)=>setItems(rows=>reorderBudgetItems(rows,bucket,before))
  const reset=()=>{setItems(priorPlan(previous));setNotice('Reset draft from last month. Save when it looks right.');setError('')}
  const save=async()=>{setSaving(true);setError('');setNotice('');const body={action:'savePlan',monthKey:month,spendingLimit:allocated,categories:items.map(({bucket,target,paced})=>({bucket,target:money(target),paced}))};try{await postJson('/api/budgets',body);setBaseline(snapshot(allocated,items));setNotice('Monthly budget saved for the family.');await onChanged()}catch(reason){setError(reason.message||'The budget could not be saved. Your draft is still here.')}finally{setSaving(false)}}

  return <section className="mb-10"><div className="flex flex-wrap items-start justify-between gap-4 mb-5"><div><h2 className="text-2xl font-black">Build the {month} budget</h2><p className="text-sm text-white/45 mt-1">Add categories and set each target. Your overall budget updates automatically.</p></div><div className="flex gap-2"><IconButton onClick={reset} icon="reset" label="Reset from last month"/><IconButton onClick={save} disabled={saving||!dirty} busy={saving} icon="save" label={saving?'Saving monthly budget':'Save monthly budget'} tone="primary"/></div></div>
    {error&&<div className="mb-4 rounded-lg border border-accent-coral/30 bg-accent-coral/10 px-4 py-3 text-sm text-accent-coral">{error}</div>}{notice&&<div className="mb-4 text-sm text-accent-green">{notice}</div>}
    <div className="grid xl:grid-cols-[minmax(0,1fr)_minmax(300px,.75fr)] gap-5 mb-6"><div className="bg-base-2 rounded-xl p-5"><div className="text-xs font-semibold uppercase tracking-wider text-white/45">Overall monthly budget</div><div className="mt-2 text-4xl font-black tabular-nums">{formatCurrency(allocated)}</div><div className="mt-3 text-sm text-white/45">Calculated from {items.length} {items.length===1?'category':'categories'}. Edit the category targets below to change this total.</div></div>
      <div className="bg-base-2 rounded-xl p-4 min-h-72"><div className="text-center font-bold">Budget allocation</div><div className="h-56 relative"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={pieData} dataKey="value" nameKey="name" innerRadius="55%" outerRadius="82%" paddingAngle={2} isAnimationActive={false}>{pieData.map((entry,index)=><Cell key={entry.name} fill={entry.empty?'#3f4654':PALETTE[index%PALETTE.length]}/>)}</Pie><Tooltip formatter={value=>formatCurrency(value)}/></PieChart></ResponsiveContainer><div className="absolute inset-0 grid place-items-center pointer-events-none"><div className="text-center"><div className="text-xl font-black">{formatCurrency(allocated)}</div><div className="text-[10px] uppercase tracking-wider text-white/40">overall budget</div></div></div></div></div></div>
    <div className="grid lg:grid-cols-[minmax(240px,.7fr)_minmax(0,1.3fr)] gap-5"><div className="bg-base-2 rounded-xl p-4 self-start"><h3 className="font-bold">Category bank</h3><p className="text-xs text-white/40 mt-1 mb-3">Previous month’s spending is used as the starting amount.</p><div className="space-y-2 max-h-[620px] overflow-auto pr-1">{bank.map(bucket=><div key={bucket} draggable onDragStart={event=>{setDragging(bucket);event.dataTransfer.setData('text/plain',bucket)}} onDragEnd={()=>setDragging('')} className={`flex items-center gap-3 rounded-lg border border-white/10 p-3 ${dragging===bucket?'opacity-50':''}`}><span className="cursor-grab text-white/30" aria-hidden>⠿</span><div className="min-w-0 flex-1"><div className="font-semibold truncate">{bucket}</div><div className="text-xs text-white/40">Previous month: {formatCurrency(priorActual[bucket]||0)}</div></div><IconButton onClick={()=>add(bucket)} icon="plus" label={`Add ${bucket}`} className="!h-9 !w-9 !basis-9"/></div>)}{!bank.length&&<div className="py-8 text-center text-sm text-white/35">Every known category is in the plan.</div>}</div></div>
      <div onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();add(event.dataTransfer.getData('text/plain'))}} className="bg-base-2 rounded-xl p-4 min-h-72"><div className="flex items-end justify-between gap-3 mb-3"><div><h3 className="font-bold">Monthly plan</h3><p className="text-xs text-white/40">Drop categories here, then tune the amounts.</p></div><span className="text-sm font-bold tabular-nums">{formatCurrency(allocated)}</span></div><div className="space-y-2">{items.map((item,index)=><BudgetCard key={item.bucket} item={item} index={index} total={items.length} actual={currentActual[item.bucket]||0} prior={priorActual[item.bucket]||0} update={update} remove={remove} move={move} setDragging={setDragging} reorder={reorder}/>)}</div>{!items.length&&<div className="grid min-h-48 place-items-center rounded-xl border-2 border-dashed border-white/10 text-center text-sm text-white/35">Drag a category here<br/>or use an Add button.</div>}</div></div>
  </section>
}

function BudgetCard({item,index,total,actual,prior,update,remove,move,setDragging,reorder}){return <div draggable onDragStart={event=>{setDragging(item.bucket);event.dataTransfer.setData('text/plan-category',item.bucket)}} onDragEnd={()=>setDragging('')} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.stopPropagation();const bucket=event.dataTransfer.getData('text/plan-category');if(bucket)reorder(bucket,item.bucket)}} className="rounded-xl border border-white/10 bg-base-1/50 p-3"><div className="flex flex-wrap items-center gap-3"><span className="cursor-grab text-white/30" aria-hidden>⠿</span><div className="min-w-[180px] flex-1"><div className="font-bold">{item.bucket}</div><div className="text-xs text-white/40">Previous month: {formatCurrency(prior)} · This month spent: {formatCurrency(actual)}</div></div><div className="flex items-center gap-1"><span className="text-white/35">$</span><input value={item.target} onChange={event=>update(item.bucket,{target:event.target.value})} className="field w-28 text-right font-bold tabular-nums" inputMode="decimal" aria-label={`${item.bucket} target`}/></div><button onClick={()=>update(item.bucket,{paced:!item.paced})} className={`text-xs px-2.5 py-2 rounded-md ${item.paced?'bg-accent-green/15 text-accent-green':'bg-white/10 text-white/55'}`}>{item.paced?'Paced':'Lumpy'}</button><div className="flex gap-1"><IconButton disabled={index===0} onClick={()=>move(index,-1)} icon="up" label={`Move ${item.bucket} up`} className="!h-9 !w-9 !basis-9"/><IconButton disabled={index===total-1} onClick={()=>move(index,1)} icon="down" label={`Move ${item.bucket} down`} className="!h-9 !w-9 !basis-9"/></div><IconButton onClick={()=>remove(item.bucket)} icon="trash" label={`Delete ${item.bucket} from this budget`} tone="danger" className="!h-9 !w-9 !basis-9"/></div></div>}
