import { useEffect,useMemo,useState } from 'react'
import { Cell,Pie,PieChart,ResponsiveContainer,Tooltip } from 'recharts'
import { formatCurrency,PALETTE } from '../lib/finance.js'
import { postJson } from '../lib/sharedState.js'
import { allocationTotals,budgetMoney as money,budgetSnapshot as snapshot,priorActualPlan as priorPlan,reorderBudgetItems } from '../lib/budgetBuilder.js'

export default function BudgetEditor({month,current,previous,categories,setting,onChanged,onDirtyChange}){
  const savedItems=useMemo(()=>(current?.pacing||[]).map(({bucket,target,paced})=>({bucket,target,paced})),[current?.pacing])
  const hasSaved=Boolean(setting)||savedItems.length>0
  const initialItems=useMemo(()=>hasSaved?savedItems:priorPlan(previous),[hasSaved,savedItems,previous])
  const initialLimit=hasSaved?(setting?.spendingLimit??savedItems.reduce((sum,row)=>sum+row.target,0)):(previous?.totalSpent||0)
  const persisted=useMemo(()=>hasSaved?snapshot(initialLimit,savedItems):snapshot(0,[]),[hasSaved,initialLimit,savedItems])
  const [limit,setLimit]=useState(initialLimit),[items,setItems]=useState(initialItems),[baseline,setBaseline]=useState(persisted),[dragging,setDragging]=useState(''),[saving,setSaving]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('')
  useEffect(()=>{setLimit(initialLimit);setItems(initialItems);setBaseline(persisted)},[month,initialLimit,initialItems,persisted])
  useEffect(()=>{setNotice('');setError('')},[month])
  const dirty=snapshot(limit,items)!==baseline
  useEffect(()=>{onDirtyChange?.(dirty)},[dirty,onDirtyChange])
  useEffect(()=>{const warn=event=>{if(!dirty)return;event.preventDefault();event.returnValue=''};addEventListener('beforeunload',warn);return()=>removeEventListener('beforeunload',warn)},[dirty])

  const priorActual=previous?.byCategory||{},currentActual=current?.byCategory||{},planned=new Set(items.map(item=>item.bucket))
  const bank=categories.filter(bucket=>!planned.has(bucket)).sort((a,b)=>(priorActual[b]||0)-(priorActual[a]||0)||a.localeCompare(b))
  const {allocated,unallocated,over}=allocationTotals(limit,items)
  const pieData=[...items.filter(item=>money(item.target)>0).map(item=>({name:item.bucket,value:money(item.target)})),...(unallocated>0?[{name:'Unallocated',value:unallocated,unallocated:true}]:[])]
  if(!pieData.length)pieData.push({name:'Unallocated',value:money(limit)||1,unallocated:true})

  const add=bucket=>{if(!bucket||planned.has(bucket))return;setItems(rows=>[...rows,{bucket,target:Number((priorActual[bucket]||0).toFixed(2)),paced:true}]);setNotice('')}
  const remove=bucket=>setItems(rows=>rows.filter(row=>row.bucket!==bucket))
  const update=(bucket,patch)=>setItems(rows=>rows.map(row=>row.bucket===bucket?{...row,...patch}:row))
  const move=(index,direction)=>setItems(rows=>{const next=[...rows],target=index+direction;if(target<0||target>=next.length)return rows;[next[index],next[target]]=[next[target],next[index]];return next})
  const reorder=(bucket,before)=>setItems(rows=>reorderBudgetItems(rows,bucket,before))
  const reset=()=>{setLimit(Number((previous?.totalSpent||0).toFixed(2)));setItems(priorPlan(previous));setNotice('Reset draft from last month. Save when it looks right.');setError('')}
  const save=async()=>{setSaving(true);setError('');setNotice('');const body={action:'savePlan',monthKey:month,spendingLimit:money(limit),categories:items.map(({bucket,target,paced})=>({bucket,target:money(target),paced}))};try{await postJson('/api/budgets',body);setBaseline(snapshot(limit,items));setNotice('Monthly budget saved for the family.');await onChanged()}catch(reason){setError(reason.message||'The budget could not be saved. Your draft is still here.')}finally{setSaving(false)}}

  return <section className="mb-10"><div className="flex flex-wrap items-start justify-between gap-4 mb-5"><div><h2 className="text-2xl font-black">Build the {month} budget</h2><p className="text-sm text-white/45 mt-1">Set the ceiling, then drag or add categories until the plan feels right.</p></div><div className="flex flex-wrap gap-2"><button onClick={reset} className="secondary-button">Reset from last month</button><button onClick={save} disabled={saving||!dirty} className="primary-button">{saving?'Saving…':'Save monthly budget'}</button></div></div>
    {error&&<div className="mb-4 rounded-lg border border-accent-coral/30 bg-accent-coral/10 px-4 py-3 text-sm text-accent-coral">{error}</div>}{notice&&<div className="mb-4 text-sm text-accent-green">{notice}</div>}
    <div className="grid xl:grid-cols-[minmax(0,1fr)_minmax(300px,.75fr)] gap-5 mb-6"><div className="bg-base-2 rounded-xl p-5"><label className="text-xs font-semibold uppercase tracking-wider text-white/45">Official monthly spending limit</label><div className="flex items-center gap-2 mt-2"><span className="text-2xl text-white/35">$</span><input value={limit} onChange={event=>setLimit(event.target.value)} className="field max-w-56 text-3xl font-black tabular-nums" inputMode="decimal" aria-label="Monthly spending limit"/></div><div className="grid sm:grid-cols-3 gap-3 mt-5"><Metric label="Allocated" value={allocated}/><Metric label="Unallocated" value={unallocated}/><Metric label="Over allocated" value={over} hot={over>0}/></div>{over>0&&<div className="mt-4 rounded-lg bg-accent-coral/10 px-3 py-2 text-sm text-accent-coral">This plan is {formatCurrency(over)} over the official limit. You can still save it.</div>}</div>
      <div className="bg-base-2 rounded-xl p-4 min-h-72"><div className="text-center font-bold">Live allocation</div><div className="h-56 relative"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={pieData} dataKey="value" nameKey="name" innerRadius="55%" outerRadius="82%" paddingAngle={2} isAnimationActive={false}>{pieData.map((entry,index)=><Cell key={entry.name} fill={entry.unallocated?'#3f4654':PALETTE[index%PALETTE.length]}/>)}</Pie><Tooltip formatter={value=>formatCurrency(value)}/></PieChart></ResponsiveContainer><div className="absolute inset-0 grid place-items-center pointer-events-none"><div className="text-center"><div className={`text-xl font-black ${over?'text-accent-coral':'text-white'}`}>{over?formatCurrency(over):formatCurrency(unallocated)}</div><div className="text-[10px] uppercase tracking-wider text-white/40">{over?'over':'left to assign'}</div></div></div></div></div></div>
    <div className="grid lg:grid-cols-[minmax(240px,.7fr)_minmax(0,1.3fr)] gap-5"><div className="bg-base-2 rounded-xl p-4 self-start"><h3 className="font-bold">Category bank</h3><p className="text-xs text-white/40 mt-1 mb-3">Previous month’s spending is used as the starting amount.</p><div className="space-y-2 max-h-[620px] overflow-auto pr-1">{bank.map(bucket=><div key={bucket} draggable onDragStart={event=>{setDragging(bucket);event.dataTransfer.setData('text/plain',bucket)}} onDragEnd={()=>setDragging('')} className={`flex items-center gap-3 rounded-lg border border-white/10 p-3 ${dragging===bucket?'opacity-50':''}`}><span className="cursor-grab text-white/30" aria-hidden>⠿</span><div className="min-w-0 flex-1"><div className="font-semibold truncate">{bucket}</div><div className="text-xs text-white/40">Previous month: {formatCurrency(priorActual[bucket]||0)}</div></div><button onClick={()=>add(bucket)} className="text-xs rounded-md bg-white/10 px-2.5 py-1.5 hover:bg-white/15" aria-label={`Add ${bucket}`}>Add</button></div>)}{!bank.length&&<div className="py-8 text-center text-sm text-white/35">Every known category is in the plan.</div>}</div></div>
      <div onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();add(event.dataTransfer.getData('text/plain'))}} className="bg-base-2 rounded-xl p-4 min-h-72"><div className="flex items-end justify-between gap-3 mb-3"><div><h3 className="font-bold">Monthly plan</h3><p className="text-xs text-white/40">Drop categories here, then tune the amounts.</p></div><span className="text-sm font-bold tabular-nums">{formatCurrency(allocated)}</span></div><div className="space-y-2">{items.map((item,index)=><BudgetCard key={item.bucket} item={item} index={index} total={items.length} actual={currentActual[item.bucket]||0} prior={priorActual[item.bucket]||0} update={update} remove={remove} move={move} setDragging={setDragging} reorder={reorder}/>)}</div>{!items.length&&<div className="grid min-h-48 place-items-center rounded-xl border-2 border-dashed border-white/10 text-center text-sm text-white/35">Drag a category here<br/>or use an Add button.</div>}</div></div>
  </section>
}

function Metric({label,value,hot}){return <div><div className="text-xs text-white/40">{label}</div><div className={`text-lg font-bold tabular-nums ${hot?'text-accent-coral':''}`}>{formatCurrency(value)}</div></div>}
function BudgetCard({item,index,total,actual,prior,update,remove,move,setDragging,reorder}){return <div draggable onDragStart={event=>{setDragging(item.bucket);event.dataTransfer.setData('text/plan-category',item.bucket)}} onDragEnd={()=>setDragging('')} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.stopPropagation();const bucket=event.dataTransfer.getData('text/plan-category');if(bucket)reorder(bucket,item.bucket)}} className="rounded-xl border border-white/10 bg-base-1/50 p-3"><div className="flex flex-wrap items-center gap-3"><span className="cursor-grab text-white/30" aria-hidden>⠿</span><div className="min-w-[180px] flex-1"><div className="font-bold">{item.bucket}</div><div className="text-xs text-white/40">Previous month: {formatCurrency(prior)} · This month spent: {formatCurrency(actual)}</div></div><div className="flex items-center gap-1"><span className="text-white/35">$</span><input value={item.target} onChange={event=>update(item.bucket,{target:event.target.value})} className="field w-28 text-right font-bold tabular-nums" inputMode="decimal" aria-label={`${item.bucket} target`}/></div><button onClick={()=>update(item.bucket,{paced:!item.paced})} className={`text-xs px-2.5 py-2 rounded-md ${item.paced?'bg-accent-green/15 text-accent-green':'bg-white/10 text-white/55'}`}>{item.paced?'Paced':'Lumpy'}</button><div className="flex"><button disabled={index===0} onClick={()=>move(index,-1)} className="px-2 py-1 text-white/50 disabled:opacity-20" aria-label={`Move ${item.bucket} up`}>↑</button><button disabled={index===total-1} onClick={()=>move(index,1)} className="px-2 py-1 text-white/50 disabled:opacity-20" aria-label={`Move ${item.bucket} down`}>↓</button></div><button onClick={()=>remove(item.bucket)} className="grid h-9 w-9 shrink-0 place-items-center rounded-md bg-accent-coral/10 text-accent-coral transition hover:bg-accent-coral/20 focus:outline-none focus:ring-2 focus:ring-accent-coral/60" aria-label={`Delete ${item.bucket} from this budget`} title={`Delete ${item.bucket}`}><TrashIcon/></button></div></div>}
function TrashIcon(){return <svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M3 6h18"/><path d="M8 6V4h8v2"/><path d="M19 6l-1 14H6L5 6"/><path d="M10 11v5M14 11v5"/></svg>}
