import { useEffect,useRef,useState } from 'react'
import { exportBudgetWorkbook } from '../lib/workbookExport.js'
import IconButton from './IconButton.jsx'

export default function ExportMenu({month,shared,portfolio}){
  const [open,setOpen]=useState(false),[busy,setBusy]=useState(''),[notice,setNotice]=useState(''),[error,setError]=useState(''),container=useRef(null)
  useEffect(()=>{const close=event=>{if(!container.current?.contains(event.target))setOpen(false)};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close)},[])
  const run=async scope=>{setOpen(false);setBusy(scope);setNotice('');setError('');try{const file=await exportBudgetWorkbook({scope,month,shared,portfolio});setNotice(`${file} downloaded`)}catch(reason){setError(reason.message||'The workbook could not be created. Please try again.')}finally{setBusy('')}}
  return <div ref={container} className="relative"><IconButton onClick={()=>setOpen(value=>!value)} disabled={Boolean(busy)||!shared.available} busy={Boolean(busy)} icon="download" label={busy?'Creating workbook':'Export budget workbook'}/>{open&&<div className="absolute right-0 z-30 mt-2 w-64 overflow-hidden rounded-xl border border-white/10 bg-base-2 shadow-2xl"><button onClick={()=>run('full')} className="block w-full px-4 py-3 text-left hover:bg-white/5"><span className="block font-bold">Complete family workbook</span><span className="text-xs text-white/45">All saved months, budgets, and uploads</span></button><button onClick={()=>run('month')} className="block w-full border-t border-white/10 px-4 py-3 text-left hover:bg-white/5"><span className="block font-bold">Selected month workbook</span><span className="text-xs text-white/45">Transactions and budget for {month}</span></button></div>}{notice&&<div className="absolute right-0 mt-2 w-72 text-right text-xs text-accent-green">{notice}</div>}{error&&<div className="absolute right-0 mt-2 w-80 text-right text-xs text-accent-coral">{error}</div>}</div>
}
