import { useEffect,useMemo,useState } from 'react'
import { Cell,Pie,PieChart,ResponsiveContainer,Tooltip } from 'recharts'
import BudgetEditor from './BudgetEditor.jsx'
import TrackerUpload from './TrackerUpload.jsx'
import CoverageStatus from './CoverageStatus.jsx'
import { formatCurrency,PALETTE } from '../lib/finance.js'
import { budgetRingData,monthlyMood } from '../lib/monthlyHome.js'
import { dateKey,dollars,monday,weeklySummary } from '../lib/weekly.js'

const periodLabel=key=>key?new Date(Number(key.slice(0,4)),Number(key.slice(5))-1,1).toLocaleString('en-US',{month:'long',year:'numeric'}):''
const currentMonthKey=()=>dateKey().slice(0,7)
const shortDate=value=>value?new Date(`${value}T00:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric'}):'—'
const weeklyMoney=value=>formatCurrency(dollars(value),{cents:true})

export default function MonthlyHomeV2({month,monthly,rows,previous,categories,setting,shared,streak,review,closeout,statusBusy,statusError,onMonthStatus,onSharedChanged,onUploaded,onOpenTransactions,onOpenWeekly,onReplay,onDirtyChange,beforeUpload,discardVersion}){
  const [editorOpen,setEditorOpen]=useState(false)
  useEffect(()=>setEditorOpen(false),[month,discardVersion])
  const hasBudget=monthly.budgetTotal>0&&monthly.pacing.length>0,hasTransactions=rows.length>0,hasImportedTransactions=rows.some(row=>row.source!=='manual'),reviewed=Boolean(review?.reviewedAt),closed=Boolean(closeout),canClose=hasBudget&&monthly.fullMonthData&&reviewed&&month<currentMonthKey()
  const currentWeek=useMemo(()=>weeklySummary(shared.transactions||[],shared.budgets||[],monday(dateKey())),[shared.transactions,shared.budgets])
  return <div className="monthly-home">
    <div className={`home-workspace ${editorOpen?'home-workspace-editor-open':''}`}>
      <div className="home-primary-column">
        <MonthlyAnswer month={month} monthly={monthly} hasBudget={hasBudget} hasTransactions={hasTransactions}/>
        <WeeklyPulse weekly={currentWeek} onOpenWeekly={onOpenWeekly}/>
        {closed?<LockedBudget month={month} monthly={monthly} closeout={closeout}/>:<section className={`instrument-panel budget-editor-shell ${editorOpen?'budget-editor-shell-open':''}`}><button type="button" className="budget-editor-toggle" onClick={()=>setEditorOpen(value=>!value)} aria-expanded={editorOpen}><span><span className="eyebrow">Monthly plan</span><strong>{hasBudget?'Edit monthly plan':'Build the monthly plan'}</strong><small>{hasBudget?`${monthly.pacing.length} categories · ${formatCurrency(monthly.budgetTotal)}`:'Set category targets before spending begins.'}</small></span><span className="disclosure-mark" aria-hidden="true">⌄</span></button><div hidden={!editorOpen} className="budget-editor-content"><BudgetEditor month={month} current={monthly} previous={previous} categories={categories} setting={setting} onChanged={onSharedChanged} onDirtyChange={onDirtyChange} discardVersion={discardVersion}/></div></section>}
      </div>
      <aside className="home-support-column">
        <Workflow month={month} monthly={monthly} hasBudget={hasBudget} hasTransactions={hasImportedTransactions} reviewed={reviewed} closed={closed} canClose={canClose} busy={statusBusy} error={statusError} onBudget={()=>setEditorOpen(true)} onReview={onOpenTransactions} onClose={()=>onMonthStatus('close')} onReopen={()=>onMonthStatus('reopen')} onReplay={onReplay}/>
        {!closed&&<TrackerUpload buttonId="rocket-upload-button" compact lastUpload={shared.lastUpload} onUploaded={onUploaded} beforeChoose={beforeUpload}/>} 
        <CategoryMix monthly={monthly}/>
        <StreakCard streak={streak}/>
      </aside>
    </div>
    <div className="home-coverage"><CoverageStatus monthly={monthly} hasTransactions={hasImportedTransactions}/></div>
  </div>
}

function MonthlyAnswer({month,monthly,hasBudget,hasTransactions}){const remaining=monthly.budgetRemaining,mood=monthlyMood({month,currentMonth:currentMonthKey(),budgetTotal:monthly.budgetTotal,transactionCount:hasTransactions?1:0,remaining,projectedTotal:monthly.projectedTotal}),over=remaining<0,used=monthly.budgetTotal>0?Math.max(0,monthly.totalSpent/monthly.budgetTotal*100):0,bar=Math.min(used,100);return <section className="instrument-panel monthly-answer"><div className="answer-heading"><div><div className="eyebrow">Monthly position</div><h1>{mood.title}</h1><p>{mood.state==='no-budget'?'Set category targets to create a plan.':mood.state==='no-data'?'Your plan is ready for the first upload or manual expense.':mood.state==='progress'?`Projected finish ${formatCurrency(monthly.projectedTotal)}.`:over?`${formatCurrency(Math.abs(remaining))} over the saved plan.`:`${formatCurrency(remaining)} remains in the saved plan.`}</p></div><span className="answer-emoji" aria-hidden="true">{mood.emoji}</span></div><div className="answer-balance"><span>{over?'Over budget':'Available'}</span><strong className={over?'negative':''}>{hasBudget?formatCurrency(Math.abs(remaining)):'—'}</strong><small>{periodLabel(month)}</small></div><div className="budget-progress" aria-label={hasBudget?`${Math.round(used)} percent of budget used`:'No monthly budget'}><span style={{width:`${bar}%`}} className={over?'budget-progress-over':''}/></div><div className="answer-metrics"><Metric label="Net profit" value={monthly.netProfit} hot={monthly.netProfit<0}/><Metric label="True spending" value={monthly.totalSpent}/><Metric label="Saved budget" value={monthly.budgetTotal}/><Metric label="Projected finish" value={monthly.projectedTotal} hot={hasBudget&&monthly.projectedTotal>monthly.budgetTotal}/></div><div className="answer-disclosures"><Disclosure title="Top expenses" summary="Five largest qualifying purchases"><Ranked rows={monthly.topExpenses.map(row=>({label:row.name,value:row.amount,detail:row.bucket}))} empty="No qualifying expenses yet."/></Disclosure><Disclosure title="Budget performance" summary="Largest category overages and unused budgets"><div className="performance-grid"><Performance title="Most over" rows={monthly.budgetPerformance?.over||[]} tone="over"/><Performance title="Most under" rows={monthly.budgetPerformance?.under||[]} tone="under"/></div></Disclosure></div></section>}
function Metric({label,value,hot}){return <div className="answer-metric"><span>{label}</span><strong className={hot?'negative':''}>{formatCurrency(value)}</strong></div>}

function WeeklyPulse({weekly,onOpenWeekly}){return <section className="instrument-panel weekly-pulse"><div className="panel-titlebar"><div><div className="eyebrow">This week</div><h2>Everyday spending</h2><p>{shortDate(weekly.start)}–{shortDate(weekly.end)}</p></div><button type="button" className="quiet-action" onClick={onOpenWeekly}>Open weekly view</button></div><div className="weekly-pulse-grid">{weekly.categories.map((category,index)=><div className="weekly-pulse-row" key={category.bucket}><div className="weekly-pulse-name"><span aria-hidden="true">{index?'🍽️':'🥦'}</span><strong>{category.bucket}</strong></div><div className="weekly-pulse-value"><strong className={category.remaining<0?'negative':''}>{category.allowance==null?'Budget not set':weeklyMoney(Math.abs(category.remaining))}</strong><small>{category.allowance==null?'Add a monthly category target':category.remaining<0?'over this week':'left this week'}</small></div>{category.allowance!=null&&<div className="weekly-mini-progress"><span style={{width:`${Math.min(100,Math.max(0,category.spent/category.allowance*100))}%`}} className={category.remaining<0?'budget-progress-over':''}/></div>}</div>)}</div></section>}

function Workflow({month,monthly,hasBudget,hasTransactions,reviewed,closed,canClose,busy,error,onBudget,onReview,onClose,onReopen,onReplay}){const steps=[{label:'Plan',detail:hasBudget?'Budget saved':'Set category targets',done:hasBudget,action:closed?null:onBudget},{label:'Upload',detail:monthly.fullMonthData?`Through ${shortDate(monthly.coverageThrough)}`:hasTransactions?`Through ${shortDate(monthly.coverageThrough)}`:'Waiting for CSV',done:hasTransactions,action:closed?null:()=>document.getElementById('rocket-upload-button')?.click()},{label:'Review',detail:reviewed?'Transactions reviewed':'Confirm categories and flows',done:reviewed,action:hasTransactions&&!closed?onReview:null},{label:'Close',detail:closed?'Month closed':canClose?'Ready for sign-off':'Complete prior steps',done:closed,action:closed?onReopen:canClose?onClose:null}];return <section className="instrument-panel workflow-panel"><div className="panel-titlebar"><div><div className="eyebrow">Monthly flow</div><h2>{periodLabel(month)}</h2></div>{closed&&<button onClick={onReplay} className="quiet-action">Wrapped</button>}</div><ol className="workflow-list">{steps.map((step,index)=><li key={step.label}><button type="button" onClick={step.action} disabled={!step.action||busy} className="workflow-step"><span className={`workflow-number ${step.done?'workflow-number-done':''}`}>{step.done?'✓':index+1}</span><span><strong>{step.label}</strong><small>{busy&&index===3?'Saving…':step.detail}</small></span><span className="workflow-chevron" aria-hidden="true">›</span></button></li>)}</ol>{error&&<div className="panel-error">{error}</div>}</section>}

function CategoryMix({monthly}){const {budget,actual,names}=budgetRingData(monthly),colors=useMemo(()=>new Map(names.map((name,index)=>[name,PALETTE[index%PALETTE.length]])),[names.join('|')]);return <section className="instrument-panel category-mix"><div className="eyebrow">Category mix</div><h2>Plan and spending</h2><div className="category-donuts"><Donut title="Budget" rows={budget} empty="No budget" total={monthly.budgetTotal} colors={colors}/><Donut title="Spent" rows={actual} empty="No spending" total={monthly.totalSpent} colors={colors}/></div><Disclosure title="Top categories" summary="Five highest spending categories"><Ranked rows={monthly.topCategories.map(row=>({label:row.bucket,value:row.amount,detail:row.highestExpense?`Highest: ${row.highestExpense.name}`:''}))} empty="No category spending yet."/></Disclosure></section>}
function Donut({title,rows,empty,total,colors}){const data=rows.length?rows:[{name:empty,value:1,empty:true}];return <div className="compact-donut"><div className="compact-donut-chart" role="img" aria-label={`${title} by category`}><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data} dataKey="value" nameKey="name" innerRadius="57%" outerRadius="84%" paddingAngle={2} isAnimationActive={false}>{data.map(row=><Cell key={row.name} fill={row.empty?'#343946':colors.get(row.name)}/>)}</Pie><Tooltip formatter={(value,name)=>[formatCurrency(value),name]}/></PieChart></ResponsiveContainer><div><strong>{rows.length?formatCurrency(total):'—'}</strong><small>{title}</small></div></div></div>}

function LockedBudget({month,monthly,closeout}){return <section className="instrument-panel locked-budget"><div className="eyebrow">Closed budget</div><h2>{periodLabel(month)} plan</h2><p>Locked {new Date(closeout.closedAt).toLocaleString()}{closeout.closedBy?` by ${closeout.closedBy}`:''}. Reopen the month from Monthly flow to edit it.</p><div className="locked-budget-grid"><Metric label="Budget" value={monthly.budgetTotal}/><Metric label="Spent" value={monthly.totalSpent}/><Metric label={monthly.budgetRemaining>=0?'Remaining':'Over budget'} value={Math.abs(monthly.budgetRemaining)} hot={monthly.budgetRemaining<0}/></div></section>}
function Disclosure({title,summary,children}){return <details className="quiet-disclosure"><summary><span><strong>{title}</strong><small>{summary}</small></span><span className="disclosure-mark" aria-hidden="true">⌄</span></summary><div className="quiet-disclosure-content">{children}</div></details>}
function Ranked({rows,empty}){return <ol className="ranked-list">{rows.length?rows.map((row,index)=><li key={`${row.label}-${index}`}><span><small>{index+1}</small><span><strong>{row.label}</strong>{row.detail&&<em>{row.detail}</em>}</span></span><b>{formatCurrency(row.value)}</b></li>):<li className="empty-row">{empty}</li>}</ol>}
function Performance({title,rows,tone}){const over=tone==='over';return <div className="performance-list"><h4>{title}</h4>{rows.length?rows.map(row=><div key={row.bucket}><span>{row.bucket}</span><strong className={over?'negative':'positive'}>{over?'+':'−'}{formatCurrency(row.difference)}</strong></div>):<p>Nothing to show.</p>}</div>}
const streakStatus={success:{mark:'✓',label:'Under budget',tone:'success'},miss:{mark:'×',label:'Over budget',tone:'miss'},'no-budget':{mark:'—',label:'No saved budget',tone:'empty'},'no-data':{mark:'·',label:'No imported data',tone:'empty'}}
function StreakCard({streak={current:0,best:0,amount:0,recent:[]}}){const latest=streak.recent.at(-1),active=streak.current>0,message=active?`${formatCurrency(streak.amount)} unused across the current streak.`:latest?.status==='miss'?`Latest closed month was ${formatCurrency(Math.abs(latest.difference))} over.`:latest?.status==='no-budget'?'Save a budget to begin.':'Complete a budgeted month to begin.';return <section className="instrument-panel streak-panel"><div className="streak-heading"><span aria-hidden="true">🔥</span><div><div className="eyebrow">Budget streak</div><h2>{active?`${streak.current} months`:'Start a streak'}</h2><p>{message}</p></div></div>{streak.recent.length>0&&<div className="streak-months">{streak.recent.map(result=>{const state=streakStatus[result.status];return <div key={result.month} title={state.label}><small>{periodLabel(result.month).slice(0,3)}</small><span className={`streak-dot streak-dot-${state.tone}`}>{state.mark}</span></div>})}</div>}<div className="streak-best">Best streak <strong>{streak.best}</strong></div></section>}
