import { useMemo,useState } from 'react'
import { LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer } from 'recharts'
import Slideshow from './Slideshow.jsx'
import TrackerUpload from './TrackerUpload.jsx'
import BudgetEditor from './BudgetEditor.jsx'
import TransactionTracker from './TransactionTracker.jsx'
import { formatCurrency } from '../lib/finance.js'
import SelectMenu from './SelectMenu.jsx'
import ExportMenu from './ExportMenu.jsx'
import { effectiveTransaction } from '../lib/tracker.js'
import { annualTrendView } from '../lib/portfolio.js'
import IconButton from './IconButton.jsx'

const tabs=[['overview','Overview'],['transactions','Transactions'],['budgets','Budgets'],['trends','Trends & YTD']]
export default function PortfolioDashboard({portfolio,archive,shared,onSharedChanged,onOverride,defaultBudgets,initialMonth}){
  const [month,setMonth]=useState(initialMonth||portfolio.currentKey),[view,setView]=useState(initialMonth?'slideshow':'overview'),[budgetDirty,setBudgetDirty]=useState(false)
  const rows=archive[month]||[],monthly=portfolio.monthly[month]||{totalSpent:0,topExpenses:[],topCategories:[],pacing:[],budgetTotal:0,budgetRemaining:0,projectedTotal:0},data=portfolio.analyses[month]
  const categories=useMemo(()=>[...new Set([...Object.values(archive).flat().map(effectiveTransaction).filter(row=>row.flow==='Expense').map(row=>row.bucket),...Object.keys(defaultBudgets),...monthly.pacing.map(r=>r.bucket),'Uncategorized'].filter(Boolean))].sort(),[archive,defaultBudgets,monthly.pacing])
  const selectedYear=month.slice(0,4),years=[...new Set([selectedYear,...portfolio.months.map(key=>key.slice(0,4))])].sort(),monthOptions=portfolio.months.filter(key=>key.startsWith(`${selectedYear}-`)).map(key=>({value:key,label:new Date(2000,Number(key.slice(5))-1,1).toLocaleString('en-US',{month:'short'})}))
  const canLeaveBudget=()=>!budgetDirty||window.confirm('Discard the unsaved monthly budget draft?')
  const selectMonth=value=>{if(value===month||!canLeaveBudget())return;setBudgetDirty(false);setMonth(value);history.replaceState(null,'',`?m=${value}`)}
  const selectYear=year=>{const sameMonth=`${year}-${month.slice(5)}`,available=portfolio.months.filter(key=>key.startsWith(`${year}-`));selectMonth(available.includes(sameMonth)?sameMonth:available.at(-1)||sameMonth)}
  const changeView=next=>{if(next!==view&&view==='budgets'&&!canLeaveBudget())return;setBudgetDirty(false);setView(next)}
  if(view==='slideshow'&&data)return <Slideshow data={data} onDone={()=>setView('overview')}/>
  const [yearNumber,monthNumber]=month.split('-').map(Number),previousKey=`${monthNumber===1?yearNumber-1:yearNumber}-${String(monthNumber===1?12:monthNumber-1).padStart(2,'0')}`,previous=portfolio.monthly[previousKey]||{totalSpent:0,byCategory:{}},setting=(shared.budgetSettings||[]).find(row=>row.monthKey===month)
  return <div className="max-w-7xl mx-auto px-5 py-8"><header className="flex items-start justify-between gap-4 mb-6"><div><div className="text-accent-green text-xs font-bold tracking-[.25em] uppercase">Budget Wrapped</div><h1 className="text-3xl font-black">Family budget tracker</h1></div><div className="flex justify-end gap-2"><ExportMenu month={month} shared={shared} portfolio={portfolio}/><IconButton onClick={()=>changeView('slideshow')} icon="replay" label="Replay Wrapped"/></div></header><div className="flex flex-wrap items-end justify-between gap-4 mb-6"><div><div className="text-xs font-semibold uppercase tracking-wider text-white/40 mb-1.5">Viewing period</div><div className="flex gap-2"><SelectMenu value={selectedYear} onChange={selectYear} options={years} label="Year" className="min-w-28"/><SelectMenu value={month} onChange={selectMonth} options={monthOptions.length?monthOptions:[{value:month,label:new Date(2000,Number(month.slice(5))-1,1).toLocaleString('en-US',{month:'short'})}]} label="Month" className="min-w-24"/></div></div><nav className="flex flex-wrap gap-2">{tabs.map(([key,label])=><button key={key} onClick={()=>changeView(key)} className={view===key?'primary-button':'secondary-button'}>{label}</button>)}</nav></div><SharedStatus shared={shared}/>{view==='overview'&&<><TrackerUpload lastUpload={shared.lastUpload} onChanged={onSharedChanged}/><StreakCard streak={portfolio.streak}/><MonthlySummary monthly={monthly}/></>}{view==='transactions'&&<TransactionTracker rows={rows} categories={categories} onOverride={onOverride}/>} {view==='budgets'&&<BudgetEditor month={month} current={monthly} previous={previous} categories={categories} setting={setting} onChanged={onSharedChanged} onDirtyChange={setBudgetDirty}/>} {view==='trends'&&<Trends portfolio={portfolio} year={selectedYear}/>}</div>
}
function SharedStatus({shared}){return shared.available?<div className="text-xs text-accent-green mb-4">● Shared family data connected</div>:<div className="bg-accent-gold/10 border border-accent-gold/30 text-accent-gold rounded-lg px-4 py-3 text-sm mb-5">Shared editing is offline. The dashboard remains readable, but uploads and edits require the local or production D1 binding.</div>}
const streakStatus={success:{mark:'✓',label:'Under budget',tone:'bg-accent-green text-base-1'},miss:{mark:'×',label:'Over budget',tone:'bg-accent-coral text-base-1'},'no-budget':{mark:'—',label:'No saved budget',tone:'bg-accent-gold/20 text-accent-gold'},'no-data':{mark:'·',label:'No imported data',tone:'bg-white/10 text-white/35'}}
const periodLabel=key=>key?new Date(Number(key.slice(0,4)),Number(key.slice(5))-1,1).toLocaleString('en-US',{month:'short',year:'numeric'}):''
function StreakCard({streak={current:0,best:0,amount:0,recent:[]}}){
  const latest=streak.recent.at(-1),active=streak.current>0
  const message=active?`Under budget by ${formatCurrency(streak.amount)} during this streak.`:latest?.status==='miss'?`The latest closed month finished ${formatCurrency(Math.abs(latest.difference))} over budget.`:latest?.status==='no-budget'?'Save a category budget for each month to start a streak.':'Complete and import a budgeted month to start your streak.'
  return <section className="mb-5 rounded-xl border border-orange-400/20 bg-gradient-to-r from-orange-400/10 to-base-2 p-5"><div className="flex flex-wrap items-center justify-between gap-5"><div className="flex min-w-[230px] items-center gap-4"><div className="grid h-14 w-14 shrink-0 place-items-center rounded-full bg-orange-400/15 text-3xl" aria-hidden="true">🔥</div><div><div className="text-xs font-semibold uppercase tracking-wider text-orange-300">Budget streak</div><h2 className="mt-0.5 text-2xl font-black">{active?`${streak.current}-month streak`:'Start your streak'}</h2><p className="mt-1 text-sm text-white/50">{message}</p>{streak.throughMonth&&<div className="mt-1 text-xs text-white/35">Through {periodLabel(streak.throughMonth)} · Best: {streak.best} {streak.best===1?'month':'months'}</div>}</div></div>{streak.recent.length>0&&<div className="flex gap-2" aria-label="Recent monthly budget results">{streak.recent.map(result=>{const state=streakStatus[result.status];return <div key={result.month} className="text-center"><div className="mb-1 text-[10px] uppercase text-white/35">{periodLabel(result.month).slice(0,3)}</div><div className={`grid h-8 w-8 place-items-center rounded-full text-sm font-black ${state.tone}`} role="img" aria-label={`${periodLabel(result.month)}: ${state.label}`} title={`${periodLabel(result.month)}: ${state.label}`}>{state.mark}</div></div>})}</div>}</div></section>
}
function MonthlySummary({monthly}){return <section className="mb-10"><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3 mb-5"><Card label="True spending" value={formatCurrency(monthly.totalSpent)}/><Card label="Monthly budget" value={formatCurrency(monthly.budgetTotal)}/><Card label="Remaining" value={formatCurrency(monthly.budgetRemaining)} hot={monthly.budgetRemaining<0}/><Card label="Projected finish" value={formatCurrency(monthly.projectedTotal)} hot={monthly.projectedTotal>monthly.budgetTotal}/></div><div className="grid lg:grid-cols-2 gap-4"><Ranked title="Top 5 expenses" rows={monthly.topExpenses.map(r=>({label:r.name,value:r.amount,sub:r.bucket}))}/><Ranked title="Top 5 categories" rows={monthly.topCategories.map(r=>({label:r.bucket,value:r.amount,detail:r.highestExpense?`Highest: ${r.highestExpense.name} · ${formatCurrency(r.highestExpense.amount)}`:'No positive expense'}))}/></div></section>}
const Card=({label,value,hot})=><div className={`bg-base-2 rounded-xl p-5 border-l-4 ${hot?'border-accent-coral':'border-accent-green'}`}><div className="text-sm text-white/45">{label}</div><div className="text-2xl font-black mt-1">{value}</div></div>
function Ranked({title,rows}){return <div className="bg-base-2 rounded-xl p-5"><h2 className="font-bold mb-3">{title}</h2><ol className="space-y-3">{rows.length?rows.map((r,i)=><li key={`${r.label}-${i}`} className="flex justify-between gap-3"><div className="min-w-0"><div><span className="text-white/35 mr-2">{i+1}.</span>{r.label}{r.sub&&<span className="text-white/35 text-xs ml-2">{r.sub}</span>}</div>{r.detail&&<div className="text-xs text-white/40 mt-0.5 ml-6 truncate">{r.detail}</div>}</div><span className="font-bold tabular-nums shrink-0">{formatCurrency(r.value)}</span></li>):<li className="text-white/35">No spending yet.</li>}</ol></div>}
const monthLabel=key=>new Date(2000,Number(key.slice(5))-1,1).toLocaleString('en-US',{month:'short'})
const axisCurrency=value=>Math.abs(value)>=1000?`$${Math.round(value/1000)}k`:`$${Math.round(value)}`
function Trends({portfolio,year}){
  const annual=useMemo(()=>annualTrendView(portfolio,year),[portfolio,year])
  const [chosen,setChosen]=useState('')
  const selected=annual.categories.find(row=>row.bucket===chosen)||annual.categories[0]
  return <><div className="grid sm:grid-cols-3 gap-3 mb-6"><Card label={`${year} spending`} value={formatCurrency(annual.actual)}/><Card label={`${year} budget`} value={formatCurrency(annual.target)}/><Card label={`${year} remaining`} value={formatCurrency(annual.difference)} hot={annual.difference<0}/></div><section className="bg-base-2 rounded-xl p-5 sm:p-6"><div className="flex flex-wrap items-end justify-between gap-4 mb-6"><div><div className="text-xs font-semibold uppercase tracking-wider text-white/40">Annual category trend</div><h2 className="text-xl font-black mt-1">{selected?.bucket||'No category data'}</h2>{selected&&<div className="text-sm text-white/45 mt-1">{formatCurrency(selected.actual)} spent · {formatCurrency(selected.target)} budgeted</div>}</div>{annual.categories.length>0&&<SelectMenu value={selected.bucket} onChange={setChosen} options={annual.categories.map(row=>({value:row.bucket,label:row.bucket}))} label="Category" className="min-w-64"/>}</div>{selected?<><div className="flex gap-5 text-xs text-white/55 mb-2"><span className="flex items-center gap-2"><i className="block w-5 h-0.5 bg-accent-green"/>Actual spending</span><span className="flex items-center gap-2"><i className="block w-5 border-t-2 border-dashed border-white/35"/>Category budget</span></div><ResponsiveContainer width="100%" height={340}><LineChart data={selected.series} margin={{top:12,right:14,left:2,bottom:2}}><XAxis dataKey="month" tickFormatter={monthLabel}/><YAxis tickFormatter={axisCurrency}/><Tooltip labelFormatter={monthLabel} formatter={(value,name)=>[formatCurrency(value),name==='actual'?'Actual spending':'Category budget']}/><Line type="monotone" dataKey="actual" stroke="#00ff87" strokeWidth={3} dot={{r:4,fill:'#00ff87'}} activeDot={{r:6}}/><Line type="monotone" dataKey="target" stroke="#6b7280" strokeWidth={2} strokeDasharray="5 5" dot={{r:3}}/></LineChart></ResponsiveContainer></>:<div className="py-20 text-center text-white/40">No spending or category budgets are available for {year}.</div>}</section></>
}
