import { useMemo,useState } from 'react'
import { LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer } from 'recharts'
import Slideshow from './Slideshow.jsx'
import TrackerUpload from './TrackerUpload.jsx'
import BudgetEditor from './BudgetEditor.jsx'
import TransactionTracker from './TransactionTracker.jsx'
import { formatCurrency } from '../lib/finance.js'
import SelectMenu from './SelectMenu.jsx'
import ExportMenu from './ExportMenu.jsx'
import { effectiveTransaction } from '../lib/tracker.js'

const tabs=[['overview','Overview'],['transactions','Transactions'],['budgets','Budgets'],['trends','Trends & YTD']]
export default function PortfolioDashboard({portfolio,archive,shared,onSharedChanged,onOverride,defaultBudgets,initialMonth}){
  const [month,setMonth]=useState(initialMonth||portfolio.currentKey),[view,setView]=useState(initialMonth?'slideshow':'overview'),[budgetDirty,setBudgetDirty]=useState(false)
  const rows=archive[month]||[],monthly=portfolio.monthly[month]||{totalSpent:0,topExpenses:[],topCategories:[],pacing:[],budgetTotal:0,budgetRemaining:0,projectedTotal:0},data=portfolio.analyses[month]
  const categories=useMemo(()=>[...new Set([...Object.values(archive).flat().map(effectiveTransaction).filter(row=>row.flow==='Expense').map(row=>row.bucket),...Object.keys(defaultBudgets),...monthly.pacing.map(r=>r.bucket),'Uncategorized'].filter(Boolean))].sort(),[archive,defaultBudgets,monthly.pacing])
  const selectedYear=month.slice(0,4),years=[...new Set([selectedYear,...portfolio.months.map(key=>key.slice(0,4))])].sort(),monthOptions=portfolio.months.filter(key=>key.startsWith(`${selectedYear}-`)).map(key=>({value:key,label:new Date(2000,Number(key.slice(5))-1,1).toLocaleString('en-US',{month:'short'})}))
  const canLeaveBudget=()=>!budgetDirty||window.confirm('Discard the unsaved monthly budget draft?')
  const selectMonth=value=>{if(value===month||!canLeaveBudget())return;setBudgetDirty(false);setMonth(value);history.replaceState(null,'',`?m=${value}`)}
  const selectYear=year=>{const sameMonth=`${year}-${month.slice(5)}`,available=portfolio.months.filter(key=>key.startsWith(`${year}-`));selectMonth(available.includes(sameMonth)?sameMonth:available.at(-1)||sameMonth)}
  const changeView=next=>{if(next!==view&&view==='budgets'&&!canLeaveBudget())return;setBudgetDirty(false);setView(next)}
  if(view==='slideshow'&&data)return <Slideshow data={data} onDone={()=>setView('overview')}/>
  const [yearNumber,monthNumber]=month.split('-').map(Number),previousKey=`${monthNumber===1?yearNumber-1:yearNumber}-${String(monthNumber===1?12:monthNumber-1).padStart(2,'0')}`,previous=portfolio.monthly[previousKey]||{totalSpent:0,byCategory:{}},setting=(shared.budgetSettings||[]).find(row=>row.monthKey===month)
  return <div className="max-w-7xl mx-auto px-5 py-8"><header className="flex items-start justify-between gap-4 mb-6"><div><div className="text-accent-green text-xs font-bold tracking-[.25em] uppercase">Budget Wrapped</div><h1 className="text-3xl font-black">Family budget tracker</h1></div><div className="flex flex-wrap justify-end gap-2"><ExportMenu month={month} shared={shared} portfolio={portfolio}/><button onClick={()=>changeView('slideshow')} className="secondary-button shrink-0">Replay Wrapped</button></div></header><div className="flex flex-wrap items-end justify-between gap-4 mb-6"><div><div className="text-xs font-semibold uppercase tracking-wider text-white/40 mb-1.5">Viewing period</div><div className="flex gap-2"><SelectMenu value={selectedYear} onChange={selectYear} options={years} label="Year" className="min-w-28"/><SelectMenu value={month} onChange={selectMonth} options={monthOptions.length?monthOptions:[{value:month,label:new Date(2000,Number(month.slice(5))-1,1).toLocaleString('en-US',{month:'short'})}]} label="Month" className="min-w-24"/></div></div><nav className="flex flex-wrap gap-2">{tabs.map(([key,label])=><button key={key} onClick={()=>changeView(key)} className={view===key?'primary-button':'secondary-button'}>{label}</button>)}</nav></div><SharedStatus shared={shared}/>{view==='overview'&&<><TrackerUpload lastUpload={shared.lastUpload} onChanged={onSharedChanged}/><MonthlySummary monthly={monthly}/></>}{view==='transactions'&&<TransactionTracker rows={rows} categories={categories} onOverride={onOverride}/>} {view==='budgets'&&<BudgetEditor month={month} current={monthly} previous={previous} categories={categories} setting={setting} onChanged={onSharedChanged} onDirtyChange={setBudgetDirty}/>} {view==='trends'&&<Trends portfolio={portfolio}/>}</div>
}
function SharedStatus({shared}){return shared.available?<div className="text-xs text-accent-green mb-4">● Shared family data connected</div>:<div className="bg-accent-gold/10 border border-accent-gold/30 text-accent-gold rounded-lg px-4 py-3 text-sm mb-5">Shared editing is offline. The dashboard remains readable, but uploads and edits require the local or production D1 binding.</div>}
function MonthlySummary({monthly}){return <section className="mb-10"><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3 mb-5"><Card label="True spending" value={formatCurrency(monthly.totalSpent)}/><Card label="Monthly budget" value={formatCurrency(monthly.budgetTotal)}/><Card label="Remaining" value={formatCurrency(monthly.budgetRemaining)} hot={monthly.budgetRemaining<0}/><Card label="Projected finish" value={formatCurrency(monthly.projectedTotal)} hot={monthly.projectedTotal>monthly.budgetTotal}/></div><div className="grid lg:grid-cols-2 gap-4"><Ranked title="Top 5 expenses" rows={monthly.topExpenses.map(r=>({label:r.name,value:r.amount,sub:r.bucket}))}/><Ranked title="Top 5 categories" rows={monthly.topCategories.map(r=>({label:r.bucket,value:r.amount,detail:r.highestExpense?`Highest: ${r.highestExpense.name} · ${formatCurrency(r.highestExpense.amount)}`:'No positive expense'}))}/></div></section>}
const Card=({label,value,hot})=><div className={`bg-base-2 rounded-xl p-5 border-l-4 ${hot?'border-accent-coral':'border-accent-green'}`}><div className="text-sm text-white/45">{label}</div><div className="text-2xl font-black mt-1">{value}</div></div>
function Ranked({title,rows}){return <div className="bg-base-2 rounded-xl p-5"><h2 className="font-bold mb-3">{title}</h2><ol className="space-y-3">{rows.length?rows.map((r,i)=><li key={`${r.label}-${i}`} className="flex justify-between gap-3"><div className="min-w-0"><div><span className="text-white/35 mr-2">{i+1}.</span>{r.label}{r.sub&&<span className="text-white/35 text-xs ml-2">{r.sub}</span>}</div>{r.detail&&<div className="text-xs text-white/40 mt-0.5 ml-6 truncate">{r.detail}</div>}</div><span className="font-bold tabular-nums shrink-0">{formatCurrency(r.value)}</span></li>):<li className="text-white/35">No spending yet.</li>}</ol></div>}
function Trends({portfolio}){const visible=portfolio.trends.filter(t=>t.series.some(x=>x.actual>0)).sort((a,b)=>Math.max(...b.series.map(x=>x.actual))-Math.max(...a.series.map(x=>x.actual)));return <><div className="grid sm:grid-cols-3 gap-3 mb-6"><Card label="YTD spending" value={formatCurrency(portfolio.ytd.actual)}/><Card label="YTD budget" value={formatCurrency(portfolio.ytd.target)}/><Card label="YTD remaining" value={formatCurrency(portfolio.ytd.difference)} hot={portfolio.ytd.difference<0}/></div><div className="grid md:grid-cols-2 gap-4">{visible.map(t=><div key={t.bucket} className="bg-base-2 p-4 rounded-xl"><h3 className="font-bold mb-2">{t.bucket}</h3><ResponsiveContainer width="100%" height={170}><LineChart data={t.series}><XAxis dataKey="month" tickFormatter={m=>m.slice(5)}/><YAxis tickFormatter={v=>`$${v}`}/><Tooltip formatter={v=>formatCurrency(v)}/><Line dataKey="actual" stroke="#00ff87" strokeWidth={2}/><Line dataKey="target" stroke="#6b7280" strokeDasharray="4 4"/></LineChart></ResponsiveContainer></div>)}</div></>}
