import { useMemo,useState } from 'react'
import { LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer } from 'recharts'
import Slideshow from './Slideshow.jsx'
import MonthlyHome from './MonthlyHome.jsx'
import TransactionTracker from './TransactionTracker.jsx'
import SelectMenu from './SelectMenu.jsx'
import ExportMenu from './ExportMenu.jsx'
import IconButton from './IconButton.jsx'
import { formatCurrency } from '../lib/finance.js'
import { effectiveTransaction } from '../lib/tracker.js'
import { annualTrendView,shiftMonth } from '../lib/portfolio.js'
import { postJson } from '../lib/sharedState.js'

const tabs=[['overview','Overview'],['transactions','Transactions'],['trends','Trends & YTD']]
const emptyMonth={totalSpent:0,topExpenses:[],topCategories:[],byCategory:{},pacing:[],budgetPerformance:{over:[],under:[]},budgetTotal:0,budgetRemaining:0,projectedTotal:0}

export default function PortfolioDashboard({portfolio,archive,shared,onSharedChanged,onOverride,defaultBudgets,initialMonth}){
  const [month,setMonth]=useState(initialMonth||portfolio.currentKey),[view,setView]=useState('overview'),[budgetDirty,setBudgetDirty]=useState(false),[discardVersion,setDiscardVersion]=useState(0),[reviewBusy,setReviewBusy]=useState(false),[reviewError,setReviewError]=useState(''),[statusBusy,setStatusBusy]=useState(false),[statusError,setStatusError]=useState('')
  const rows=archive[month]||[],monthly=portfolio.monthly[month]||emptyMonth,data=portfolio.analyses[month]
  const categories=useMemo(()=>[...new Set([...Object.values(archive).flat().map(effectiveTransaction).filter(row=>row.flow==='Expense').map(row=>row.bucket),...Object.keys(defaultBudgets),...monthly.pacing.map(row=>row.bucket),'Uncategorized'].filter(Boolean))].sort(),[archive,defaultBudgets,monthly.pacing])
  const selectedYear=month.slice(0,4),years=[...new Set([selectedYear,...portfolio.months.map(key=>key.slice(0,4))])].sort(),monthOptions=portfolio.months.filter(key=>key.startsWith(`${selectedYear}-`)).map(key=>({value:key,label:new Date(2000,Number(key.slice(5))-1,1).toLocaleString('en-US',{month:'short'})}))
  const previousKey=shiftMonth(month,-1),previous=portfolio.monthly[previousKey]||emptyMonth,setting=(shared.budgetSettings||[]).find(row=>row.monthKey===month),review=(shared.monthlyReviews||[]).find(row=>row.monthKey===month),closeout=(shared.monthlyCloseouts||[]).find(row=>row.monthKey===month),locked=Boolean(closeout)
  const discardDraft=message=>{if(!budgetDirty)return true;if(!window.confirm(message))return false;setBudgetDirty(false);setDiscardVersion(value=>value+1);return true}
  const selectMonth=value=>{if(value===month||!discardDraft('Discard the unsaved monthly budget draft?'))return;setMonth(value);history.replaceState(null,'',`?m=${value}`)}
  const selectYear=year=>{const sameMonth=`${year}-${month.slice(5)}`,available=portfolio.months.filter(key=>key.startsWith(`${year}-`));selectMonth(available.includes(sameMonth)?sameMonth:available.at(-1)||sameMonth)}
  const changeView=next=>{if(next!==view&&view==='overview'&&!discardDraft('Discard the unsaved monthly budget draft?'))return;setView(next)}
  const beforeUpload=()=>locked?false:discardDraft('Discard the unsaved monthly budget draft and choose a Rocket Money CSV?')
  const handleUploaded=async result=>{await onSharedChanged();if(result.latestMonth){setMonth(result.latestMonth);history.replaceState(null,'',`?m=${result.latestMonth}`)}setReviewError('');setView('transactions')}
  const completeReview=async()=>{if(!review)return;setReviewBusy(true);setReviewError('');try{await postJson('/api/review',{monthKey:month,uploadEventId:review.uploadEventId});await onSharedChanged()}catch(error){setReviewError(error.message)}finally{setReviewBusy(false)}}
  const changeMonthStatus=async action=>{const verb=action==='close'?'Close':'Reopen';if(!window.confirm(`${verb} ${monthLabelLong(month)}?`))return;setStatusBusy(true);setStatusError('');try{await postJson('/api/month-status',{action,monthKey:month});await onSharedChanged();if(action==='close'){const next=shiftMonth(month,1);setMonth(next);setView('overview');history.replaceState(null,'',`?m=${next}`)}}catch(error){setStatusError(error.message)}finally{setStatusBusy(false)}}
  if(view==='slideshow'&&data)return <Slideshow data={data} onDone={()=>setView('overview')}/>
  return <div className="mx-auto max-w-7xl px-5 py-8"><header className="mb-6 flex items-start justify-between gap-4"><div><div className="text-xs font-bold uppercase tracking-[.25em] text-accent-green">Budget Wrapped</div><h1 className="text-3xl font-black">Family budget tracker</h1></div><div className="flex justify-end gap-2"><ExportMenu month={month} shared={shared} portfolio={portfolio}/><IconButton onClick={()=>changeView('slideshow')} disabled={!data||!rows.length} icon="replay" label="Replay Wrapped"/></div></header>
    <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><div className="mb-1.5 text-xs font-semibold uppercase tracking-wider text-white/40">Viewing period</div><div className="flex gap-2"><SelectMenu value={selectedYear} onChange={selectYear} options={years} label="Year" className="min-w-28"/><SelectMenu value={month} onChange={selectMonth} options={monthOptions} label="Month" className="min-w-24"/></div></div><nav className="flex flex-wrap gap-2">{tabs.map(([key,label])=><button key={key} onClick={()=>changeView(key)} className={view===key?'primary-button':'secondary-button'}>{label}</button>)}</nav></div>
    <SharedStatus shared={shared}/>
    {view==='overview'&&<MonthlyHome month={month} monthly={monthly} rows={rows} previous={previous} categories={categories} setting={setting} shared={shared} streak={portfolio.streak} review={review} closeout={closeout} statusBusy={statusBusy} statusError={statusError} onMonthStatus={changeMonthStatus} onSharedChanged={onSharedChanged} onUploaded={handleUploaded} onOpenTransactions={()=>changeView('transactions')} onReplay={()=>changeView('slideshow')} onDirtyChange={setBudgetDirty} beforeUpload={beforeUpload} discardVersion={discardVersion}/>}
    {view==='transactions'&&<TransactionTracker rows={rows} categories={categories} onOverride={onOverride} review={review} busy={reviewBusy} error={reviewError} onReview={completeReview} locked={locked}/>}
    {view==='trends'&&<Trends portfolio={portfolio} year={selectedYear}/>}</div>
}
function SharedStatus({shared}){return shared.available?<div className="mb-4 text-xs text-accent-green">● Shared family data connected</div>:<div className="mb-5 rounded-lg border border-accent-gold/30 bg-accent-gold/10 px-4 py-3 text-sm text-accent-gold">Shared editing is offline. The dashboard remains readable, but uploads and edits require D1.</div>}
const Card=({label,value,hot})=><div className={`rounded-xl border-l-4 bg-base-2 p-5 ${hot?'border-accent-coral':'border-accent-green'}`}><div className="text-sm text-white/45">{label}</div><div className="mt-1 text-2xl font-black">{value}</div></div>
const monthLabel=key=>new Date(2000,Number(key.slice(5))-1,1).toLocaleString('en-US',{month:'short'}),monthLabelLong=key=>new Date(Number(key.slice(0,4)),Number(key.slice(5))-1,1).toLocaleString('en-US',{month:'long',year:'numeric'}),axisCurrency=value=>Math.abs(value)>=1000?`$${Math.round(value/1000)}k`:`$${Math.round(value)}`
function Trends({portfolio,year}){const annual=useMemo(()=>annualTrendView(portfolio,year),[portfolio,year]),[chosen,setChosen]=useState(''),selected=annual.categories.find(row=>row.bucket===chosen)||annual.categories[0];return <><div className="mb-6 grid gap-3 sm:grid-cols-3"><Card label={`${year} spending`} value={formatCurrency(annual.actual)}/><Card label={`${year} budget`} value={formatCurrency(annual.target)}/><Card label={`${year} remaining`} value={formatCurrency(annual.difference)} hot={annual.difference<0}/></div><section className="rounded-xl bg-base-2 p-5 sm:p-6"><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><div className="text-xs font-semibold uppercase tracking-wider text-white/40">Annual category trend</div><h2 className="mt-1 text-xl font-black">{selected?.bucket||'No category data'}</h2>{selected&&<div className="mt-1 text-sm text-white/45">{formatCurrency(selected.actual)} spent · {formatCurrency(selected.target)} budgeted</div>}</div>{annual.categories.length>0&&<SelectMenu value={selected.bucket} onChange={setChosen} options={annual.categories.map(row=>({value:row.bucket,label:row.bucket}))} label="Category" className="min-w-64"/>}</div>{selected?<><div className="mb-2 flex gap-5 text-xs text-white/55"><span>Actual spending</span><span>Category budget</span></div><ResponsiveContainer width="100%" height={340}><LineChart data={selected.series}><XAxis dataKey="month" tickFormatter={monthLabel}/><YAxis tickFormatter={axisCurrency}/><Tooltip labelFormatter={monthLabel} formatter={(value,name)=>[formatCurrency(value),name==='actual'?'Actual spending':'Category budget']}/><Line type="monotone" dataKey="actual" stroke="#00ff87" strokeWidth={3}/><Line type="monotone" dataKey="target" stroke="#6b7280" strokeWidth={2} strokeDasharray="5 5"/></LineChart></ResponsiveContainer></>:<div className="py-20 text-center text-white/40">No spending or category budgets are available for {year}.</div>}</section></>}
