import { useMemo,useState } from 'react'
import { formatCurrency } from '../lib/finance.js'
import { FLOW_TYPES } from '../lib/tracker.js'
import { postJson } from '../lib/sharedState.js'
import SelectMenu from './SelectMenu.jsx'

export default function TransactionTracker({rows,categories,onOverride,review,busy,error,onReview,locked=false,onEditManual,onChanged}){
  const [query,setQuery]=useState(''),[category,setCategory]=useState('All'),[flow,setFlow]=useState('All'),[account,setAccount]=useState('All'),[sort,setSort]=useState({key:'date',dir:'desc'}),[editError,setEditError]=useState('')
  const accounts=[...new Set(rows.map(r=>r.account).filter(Boolean))].sort()
  const filtered=useMemo(()=>rows.filter(r=>(!query||`${r.name} ${r.bucket} ${r.rawCategory}`.toLowerCase().includes(query.toLowerCase()))&&(category==='All'||r.bucket===category)&&(flow==='All'||r.flow===flow)&&(account==='All'||r.account===account)).sort((a,b)=>{const av=a[sort.key]??'',bv=b[sort.key]??'',result=typeof av==='number'?av-bv:String(av).localeCompare(String(bv));return sort.dir==='asc'?result:-result}),[rows,query,category,flow,account,sort])
  const change=async(row,patch)=>{if(locked)return;setEditError('');try{await onOverride(row,patch)}catch(e){setEditError(e.message)}}
  const remove=async row=>{if(!window.confirm('Delete this manual expense? It will leave spending totals but remain in the audit export.'))return;try{await postJson('/api/manual',{action:'delete',txnKey:row.txnKey});await onChanged()}catch(reason){setEditError(reason.message)}}
  const toggle=key=>setSort(s=>({key,dir:s.key===key&&s.dir==='desc'?'asc':'desc'}))
  const reviewed=Boolean(review?.reviewedAt),canReview=Boolean(review)&&!reviewed&&!locked
  return <section><div className="mb-3 flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-bold">Transaction tracking</h2><p className="text-sm text-white/45">{filtered.length} rows · {formatCurrency(filtered.filter(r=>r.flow==='Expense').reduce((s,r)=>s+r.amount,0))} true spending</p>{locked&&<p className="mt-1 text-xs text-accent-gold">This month is closed. Reopen it from Overview to make corrections.</p>}</div><div className="text-right">{reviewed?<div className="rounded-lg border border-accent-green/25 bg-accent-green/10 px-4 py-2 text-sm font-bold text-accent-green">✓ Reviewed</div>:<button onClick={onReview} disabled={!canReview||busy} className="primary-button">{busy?'Saving…':'Mark reviewed'}</button>}{!review&&<div className="mt-1 text-xs text-white/35">Upload this month before reviewing.</div>}{reviewed&&<div className="mt-1 text-xs text-white/35">{review.reviewedBy||'Family member'} · {new Date(review.reviewedAt).toLocaleString()}</div>}</div></div>
    {(error||editError)&&<div className="mb-3 text-sm text-accent-coral">{error||editError}</div>}
    <div className="mb-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><input className="field" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search expense…"/><Filter value={category} set={setCategory} values={categories} label="All categories"/><Filter value={flow} set={setFlow} values={FLOW_TYPES} label="All flow types"/><Filter value={account} set={setAccount} values={accounts} label="All accounts"/></div>
    <div className="max-h-[620px] overflow-auto rounded-xl bg-base-2"><table className="w-full min-w-[980px] text-sm"><thead className="sticky top-0 z-10 bg-base-2"><tr className="text-white/45"><Th label="Date" k="date" toggle={toggle}/><Th label="Expense / merchant" k="name" toggle={toggle}/><Th label="Amount" k="amount" toggle={toggle}/><th>Category</th><th>Flow type</th><th>Account</th><th>Rocket Money category</th></tr></thead><tbody>{filtered.map(row=><tr key={row.txnKey||`${row.date}|${row.amount}|${row.name}|${row.account}`} className={`border-t border-white/5 ${row.overrideBucket||row.overrideFlow?'bg-accent-purple/5':''}`}><td className="whitespace-nowrap">{new Date(`${row.date}T00:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric'})}</td><td className="font-medium">{row.name}{row.source==='manual'&&<div className="mt-1 flex gap-2 text-xs"><span className="text-accent-sky">MANUAL</span><button disabled={locked} className="secondary-button" onClick={()=>onEditManual(row)}>Edit</button><button disabled={locked} className="secondary-button text-accent-coral" aria-label={`Delete ${row.name}`} onClick={()=>remove(row)}>Delete</button></div>}{(row.overrideBucket||row.overrideFlow)&&<span className="ml-2 text-[10px] text-accent-purple">EDITED</span>}</td><td className="tabular-nums">{formatCurrency(row.amount,{cents:true})}</td><td><SelectMenu value={row.bucket} onChange={value=>change(row,{bucket:value})} options={categories} label="Transaction category" className="w-48" disabled={locked}/></td><td><SelectMenu value={row.flow} onChange={value=>change(row,{flow:value})} options={FLOW_TYPES} label="Flow type" className="w-36" disabled={locked}/></td><td className="text-white/55">{row.account||'—'}</td><td className="text-white/45">{row.rawCategory||'—'}</td></tr>)}</tbody></table></div>
  </section>
}
function Filter({value,set,values,label}){return <SelectMenu value={value} onChange={set} options={[{value:'All',label},...values.map(item=>({value:item,label:item}))]} label={label}/>}
function Th({label,k,toggle}){return <th><button onClick={()=>toggle(k)} className="py-3 text-left">{label} ↕</button></th>}
