import { useEffect,useMemo,useState } from 'react'
import { formatCurrency } from '../lib/finance.js'
import { FLOW_TYPES,spendingAudit,transactionDisposition } from '../lib/tracker.js'
import { postJson } from '../lib/sharedState.js'
import SelectMenu from './SelectMenu.jsx'
import IconButton from './IconButton.jsx'

export default function TransactionTrackerV2({rows,categories,preset,onOverride,review,busy,error,onReview,locked=false,onEditManual,onChanged}){
  const [query,setQuery]=useState(''),[category,setCategory]=useState('All'),[flow,setFlow]=useState('All'),[account,setAccount]=useState('All'),[activePreset,setActivePreset]=useState(preset),[sort,setSort]=useState({key:'date',dir:'desc'}),[editError,setEditError]=useState('')
  useEffect(()=>{setActivePreset(preset);if(preset){setQuery('');setCategory('All');setFlow('All');setAccount('All')}},[preset])
  const accounts=[...new Set(rows.map(row=>row.account).filter(Boolean))].sort()
  const filtered=useMemo(()=>rows.filter(row=>(!query||`${row.name} ${row.bucket} ${row.rawCategory}`.toLowerCase().includes(query.toLowerCase()))&&(category==='All'||row.bucket===category)&&(flow==='All'||row.flow===flow)&&(account==='All'||row.account===account)&&matchesPreset(row,activePreset)).sort((a,b)=>{const av=a[sort.key]??'',bv=b[sort.key]??'',result=typeof av==='number'?av-bv:String(av).localeCompare(String(bv));return sort.dir==='asc'?result:-result}),[rows,query,category,flow,account,activePreset,sort])
  const audit=useMemo(()=>spendingAudit(rows),[rows]),filteredAudit=useMemo(()=>spendingAudit(filtered),[filtered]),reviewCount=audit.needsReview.uncategorized+audit.needsReview.cashAndChecks+audit.needsReview.ambiguousMatches
  const resetPreset=()=>setActivePreset(null),manualSet=setter=>value=>{setter(value);resetPreset()}
  const change=async(row,patch)=>{if(locked)return;setEditError('');try{await onOverride(row,patch)}catch(reason){setEditError(reason.message)}}
  const remove=async row=>{if(!window.confirm('Delete this manual expense? It will leave spending totals but remain in the audit export.'))return;try{await postJson('/api/manual',{action:'delete',txnKey:row.txnKey});await onChanged()}catch(reason){setEditError(reason.message)}}
  const toggle=key=>setSort(current=>({key,dir:current.key===key&&current.dir==='desc'?'asc':'desc'}))
  const reviewed=Boolean(review?.reviewedAt),canReview=Boolean(review)&&!reviewed&&!locked
  return <section className="transaction-workspace"><header className="transaction-heading"><div><div className="eyebrow">Monthly ledger</div><h1>Transactions</h1><p>{filtered.length} rows · {formatCurrency(filteredAudit.trueSpending)} true spending</p>{locked&&<small>This month is closed. Reopen it from Overview to make corrections.</small>}</div><div className="review-state">{reviewed?<div className="reviewed-badge">✓ Reviewed</div>:<button onClick={onReview} disabled={!canReview||busy} className="primary-button">{busy?'Saving…':'Mark reviewed'}</button>}{!review&&<small>Upload this month before reviewing.</small>}{reviewed&&<small>{review.reviewedBy||'Family member'} · {new Date(review.reviewedAt).toLocaleString()}</small>}</div></header>
    {(error||editError)&&<div className="app-notice app-notice-error">{error||editError}</div>}
    {reviewCount>0&&<div className="transaction-review-warning"><strong>{reviewCount} items deserve review</strong><span>They still count according to their current flow.</span><div>{audit.needsReview.uncategorized>0&&<button onClick={()=>setActivePreset({review:'uncategorized',label:'Uncategorized'})}>{audit.needsReview.uncategorized} uncategorized</button>}{audit.needsReview.cashAndChecks>0&&<button onClick={()=>setActivePreset({review:'cash',label:'Cash & Checks'})}>{audit.needsReview.cashAndChecks} cash/check</button>}{audit.needsReview.ambiguousMatches>0&&<button onClick={()=>setActivePreset({review:'ambiguous',label:'Possible duplicates'})}>{audit.needsReview.ambiguousMatches} possible duplicates</button>}</div></div>}
    {activePreset&&<div className="transaction-filter-chip"><span>Audit filter: <strong>{activePreset.label}</strong></span><button onClick={resetPreset}>Clear</button></div>}
    <div className="transaction-toolbar"><input className="field transaction-search" value={query} onChange={event=>manualSet(setQuery)(event.target.value)} placeholder="Search merchant, category…" aria-label="Search transactions"/><Filter value={category} set={manualSet(setCategory)} values={categories} label="All categories"/><Filter value={flow} set={manualSet(setFlow)} values={FLOW_TYPES} label="All flow types"/><Filter value={account} set={manualSet(setAccount)} values={accounts} label="All accounts"/></div>
    <div className="transaction-table-wrap"><table className="transaction-table"><thead><tr><Th label="Date" name="date" toggle={toggle}/><Th label="Expense / merchant" name="name" toggle={toggle}/><Th label="Amount" name="amount" toggle={toggle}/><th>Category</th><th>Flow</th><th>Account</th><th>Original category</th></tr></thead><tbody>{filtered.map(row=><tr key={row.txnKey||`${row.date}|${row.amount}|${row.name}|${row.account}`} className={row.overrideBucket||row.overrideFlow?'transaction-overridden':''}><td className="transaction-date">{new Date(`${row.date}T00:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric'})}</td><td><div className="merchant-cell"><span>{row.name}</span><span className="transaction-badges">{row.source==='manual'&&<i className="source-badge source-badge-manual">Manual</i>}{(row.overrideBucket||row.overrideFlow)&&<i className="source-badge source-badge-edited">Edited</i>}{String(row.bucket||'').trim().toLowerCase()==='uncategorized'&&<i className="source-badge source-badge-warning">Needs category</i>}{isCashCategory(row.bucket)&&<i className="source-badge source-badge-warning">Verify cash</i>}{row.matchStatus==='ambiguous'&&<i className="source-badge source-badge-warning">Possible duplicate</i>}</span>{row.source==='manual'&&<span className="transaction-row-actions"><button disabled={locked} className="quiet-action" onClick={()=>onEditManual(row)}>Edit</button><IconButton disabled={locked} onClick={()=>remove(row)} icon="trash" tone="danger" label={`Delete ${row.name}`} className="!h-8 !w-8 !basis-8"/></span>}</div></td><td className="tabular-nums">{formatCurrency(row.amount,{cents:true})}</td><td><SelectMenu value={row.bucket} onChange={value=>change(row,{bucket:value})} options={categories} label="Transaction category" className="w-44" disabled={locked}/></td><td><SelectMenu value={row.flow} onChange={value=>change(row,{flow:value})} options={FLOW_TYPES} label="Flow type" className="w-32" disabled={locked}/></td><td>{row.account||'—'}</td><td>{row.rawCategory||'—'}</td></tr>)}</tbody></table>{!filtered.length&&<div className="empty-action">No transactions match these filters. Clear a filter or add an expense.</div>}</div>
  </section>
}
const isCashCategory=value=>/^cash (?:&|and) checks?$/.test(String(value||'').trim().toLowerCase())
function matchesPreset(row,preset){if(!preset)return true;const disposition=transactionDisposition(row),bucket=String(disposition.row.bucket||'').trim().toLowerCase();if(preset.flow&&disposition.row.flow!==preset.flow)return false;if(preset.kind&&disposition.kind!==preset.kind)return false;if(preset.review==='uncategorized'&&bucket!=='uncategorized')return false;if(preset.review==='cash'&&!isCashCategory(bucket))return false;if(preset.review==='ambiguous'&&row.matchStatus!=='ambiguous')return false;return true}
function Filter({value,set,values,label}){return <SelectMenu value={value} onChange={set} options={[{value:'All',label},...values.map(item=>({value:item,label:item}))]} label={label}/>} 
function Th({label,name,toggle}){return <th><button onClick={()=>toggle(name)}>{label}<span aria-hidden="true">↕</span></button></th>}
