import { useEffect, useState } from 'react'
import { cents, dateKey, dollars, incomeSuggestion, monday, recommendWeekly, shiftDay, weeklyBaselines, weeklySummary, WEEKLY_CATEGORIES } from '../lib/weekly.js'
import { formatCurrency } from '../lib/finance.js'
import { postJson } from '../lib/sharedState.js'

const money = value => formatCurrency(dollars(value), { cents: true })
const labelMonth = key => new Date(`${key}-01T12:00:00`).toLocaleDateString('en-US', { month: 'long', year: 'numeric' })
export default function WeeklyBudget({ month, shared, onChanged, onDirtyChange }) {
  const [week, setWeek] = useState(monday(dateKey()))
  const weekly = weeklySummary(shared.transactions || [], shared.budgets || [], week)
  return <section className="space-y-6">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-2xl font-black">Your weekly spending</h2><p className="mt-1 text-sm text-white/50">Monday–Sunday · Fresh allowances each week, with no rollover.</p></div><div className="flex flex-wrap items-center gap-2"><button className="secondary-button" aria-label="Previous week" onClick={() => setWeek(shiftDay(week, -7))}>←</button><label className="text-xs text-white/55">Week containing<input aria-label="Week containing date" type="date" value={week} onChange={e => e.target.value && setWeek(monday(e.target.value))} className="field ml-2"/></label><button className="secondary-button" aria-label="Next week" onClick={() => setWeek(shiftDay(week, 7))}>→</button><button className="secondary-button" onClick={() => setWeek(monday(dateKey()))}>This week</button></div></div>
    <p className="text-sm text-white/55">{weekly.start} through {weekly.end}. Allowance comes from the saved monthly targets for these dates.</p>
    <div className="grid gap-4 md:grid-cols-2">{weekly.categories.map((category, index) => <section key={category.bucket} className="rounded-xl border border-white/10 bg-base-2 p-5"><div className="text-2xl" aria-hidden="true">{index ? '🍽️' : '🥦'}</div><h3 className="mt-2 text-xl font-bold">{category.bucket}</h3><div className={`mt-3 text-3xl font-black ${category.remaining < 0 ? 'text-accent-coral' : 'text-accent-green'}`}>{category.allowance == null ? 'Budget not set' : money(Math.abs(category.remaining))}</div><p className="text-sm text-white/55">{category.allowance == null ? `Missing targets: ${category.missing.join(', ')}` : category.remaining < 0 ? 'over this week’s allowance' : 'left this week'}</p><div className="my-4 flex justify-between text-sm"><span>{money(category.spent)} spent</span><span>{category.allowance == null ? '—' : `${money(category.allowance)} allowance`}</span></div>{category.allowance != null && <progress aria-label={`${category.bucket} allowance used`} value={Math.max(0, category.spent)} max={Math.max(1, category.allowance)} className={`h-2 w-full ${category.spent > category.allowance ? 'accent-red-400' : category.spent >= category.allowance * .8 ? 'accent-yellow-400' : 'accent-green-400'}`}/>}
      <details className="mt-4"><summary className="cursor-pointer text-sm font-semibold">Purchases ({category.transactions.length})</summary><ul className="mt-3 space-y-2 text-sm">{category.transactions.map(row => <li key={row.txnKey} className="flex justify-between gap-3"><span>{row.date.slice(5)} · {row.name}{row.source === 'manual' ? ' · manual' : ''}</span><span className="shrink-0 tabular-nums">{formatCurrency(row.amount, { cents: true })}</span></li>)}{!category.transactions.length && <li className="text-white/45">No recorded purchases yet. Manual entries appear immediately.</li>}</ul></details>
    </section>)}</div>
    <SavingsPlanner key={month} month={month} shared={shared} onChanged={onChanged} onDirtyChange={onDirtyChange}/>
  </section>
}

function SavingsPlanner({ month, shared, onChanged, onDirtyChange }) {
  const saved = (shared.savingsSettings || []).find(row => row.monthKey === month)
  const history = weeklyBaselines(shared.transactions || [], shared.importCoverage || [], month < dateKey().slice(0, 7) ? `${month}-01` : dateKey())
  const income = incomeSuggestion(shared.transactions || [], shared.monthlyReviews || [], `${month}-01`, shared.importCoverage || [])
  const targets = WEEKLY_CATEGORIES.map(bucket => (shared.budgets || []).find(row => row.monthKey === month && row.bucket === bucket)?.target)
  const [form, setForm] = useState(() => ({ income: saved ? dollars(saved.income) : income.amount == null ? '' : dollars(income.amount), savings: saved ? dollars(saved.savings) : 1000, groceriesBaseline: saved ? dollars(saved.groceriesBaseline) : history.categories[0].monthly == null ? '' : dollars(history.categories[0].monthly), restaurantsBaseline: saved ? dollars(saved.restaurantsBaseline) : history.categories[1].monthly == null ? '' : dollars(history.categories[1].monthly), groceries: targets[0] ?? '', restaurants: targets[1] ?? '' }))
  const [incomeConfirmed, setIncomeConfirmed] = useState(false), [commitmentsConfirmed, setCommitmentsConfirmed] = useState(false), [dirty, setDirty] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('')
  const locked = (shared.monthlyCloseouts || []).some(row => row.monthKey === month)
  const other = (shared.budgets || []).filter(row => row.monthKey === month && !WEEKLY_CATEGORIES.includes(row.bucket)).reduce((sum, row) => sum + cents(row.target), 0)
  const recommendation = recommendWeekly({ income: cents(form.income), savings: cents(form.savings), other, groceries: cents(form.groceriesBaseline), restaurants: cents(form.restaurantsBaseline) })
  const balance = cents(form.income) - cents(form.savings) - other - cents(form.groceries) - cents(form.restaurants)
  const basesReady = form.groceriesBaseline !== '' && form.restaurantsBaseline !== '' && form.income !== ''
  useEffect(() => { onDirtyChange(dirty); return () => onDirtyChange(false) }, [dirty, onDirtyChange])
  useEffect(() => { if (!dirty) return; const warn = e => { e.preventDefault(); e.returnValue = '' }; window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn) }, [dirty])
  const update = (key, value) => { setForm(current => ({ ...current, [key]: value })); setDirty(true); setNotice('') }
  const save = async e => {
    e.preventDefault(); setBusy(true); setError(''); setNotice('')
    try { await postJson('/api/weekly-plan', { monthKey: month, ...Object.fromEntries(Object.entries(form).map(([key, value]) => [key, cents(value)])), incomeConfirmed, commitmentsConfirmed }); setDirty(false); await onChanged(); setNotice('Saved for the family. Monthly targets and weekly allowances are updated.') }
    catch (reason) { setError(reason.message) } finally { setBusy(false) }
  }
  return <form onSubmit={save} className="rounded-xl border border-accent-green/20 bg-base-2 p-5 sm:p-6"><div className="text-xs font-semibold uppercase tracking-wider text-accent-green">Savings first</div><h2 className="mt-1 text-2xl font-black">Plan {labelMonth(month)}</h2><p className="mt-2 text-sm text-white/55">Reserve savings and other commitments, then plan groceries and dining. Nothing changes until you save.</p>
    {locked && <p className="mt-3 text-accent-gold">This month is closed. Reopen it from Overview to change its plan.</p>}
    <fieldset disabled={locked || busy || !shared.available} className="mt-5 space-y-5">
      <div className="grid gap-4 sm:grid-cols-2"><MoneyInput label="Expected monthly take-home income" value={form.income} onChange={value => { update('income', value); setIncomeConfirmed(false) }}/><MoneyInput label="Monthly savings target" value={form.savings} onChange={value => update('savings', value)}/></div>
      <p className="text-xs text-white/50">{income.amount == null ? 'No reviewed income history yet. Enter your expected take-home income.' : `Income suggestion: ${money(income.amount)}, averaged from ${income.months.join(', ')}. Confirm it accounts for irregular pay.`}</p>
      <label className="flex gap-3 text-sm"><input type="checkbox" checked={incomeConfirmed} onChange={e => setIncomeConfirmed(e.target.checked)}/>I confirm this expected income for {labelMonth(month)}.</label>
      <div className="rounded-lg bg-white/5 p-4"><div className="flex flex-wrap justify-between gap-2"><span>Other saved category targets</span><strong>{money(other)}</strong></div><label className="mt-3 flex gap-3 text-sm"><input type="checkbox" checked={commitmentsConfirmed} onChange={e => setCommitmentsConfirmed(e.target.checked)}/>These targets include our other bills and commitments, without double-counting savings.</label></div>
      <div><h3 className="font-bold">Spending baselines</h3><p className="mt-1 text-xs text-white/50">{history.weeks} covered weeks out of the trailing 12 completed weeks. {history.weeks < 4 ? 'Insufficient history: enter monthly baselines below.' : 'Median weekly spending × 52 ÷ 12. Groceries round up to the nearest $5 per week.'} Only confirmed CSV coverage establishes zero-spending days.</p><div className="mt-3 grid gap-4 sm:grid-cols-2">{['groceriesBaseline', 'restaurantsBaseline'].map((key, index) => <MoneyInput key={key} label={`${index ? 'Restaurant' : 'Grocery'} monthly baseline`} value={form[key]} onChange={value => update(key, value)}/>)}</div></div>
      <div className="rounded-lg border border-white/10 p-4"><div className="text-sm text-white/55">Income − savings − other targets</div><div className="text-2xl font-black">{form.income===''?'Confirm income to calculate':`${money(recommendation.available)} available`}</div><p className="mt-2 text-sm" title="Groceries receive their baseline first, restaurants receive the remaining capacity up to their baseline.">Recommendation: {basesReady ? `${money(recommendation.groceries)} groceries + ${money(recommendation.restaurants)} restaurants` : 'Enter income and both baselines first.'}</p>{basesReady && recommendation.shortfall > 0 && <p role="status" className="mt-2 text-sm text-accent-coral">Shortfall: {money(recommendation.shortfall)} before grocery needs fit. Adjust income, commitments, or your baseline explicitly; savings will not be reduced automatically.</p>}<button type="button" className="secondary-button mt-3" disabled={!basesReady || recommendation.shortfall > 0} onClick={() => { update('groceries', dollars(recommendation.groceries)); update('restaurants', dollars(recommendation.restaurants)) }}>Use recommended targets</button></div>
      <div className="grid gap-4 sm:grid-cols-2"><MoneyInput label="My grocery monthly target" value={form.groceries} onChange={value => update('groceries', value)}/><MoneyInput label="My restaurant monthly target" value={form.restaurants} onChange={value => update('restaurants', value)}/></div>
      <div className="flex flex-wrap items-center justify-between gap-3"><div><div className={form.income!==''&&balance < 0 ? 'font-bold text-accent-coral' : 'font-bold text-accent-green'}>{form.income===''?'Enter expected income first':balance < 0 ? `${money(-balance)} over available income` : `${money(balance)} potential additional savings`}</div><p className="mt-1 text-xs text-white/45">A plan, not a bank transfer or guaranteed cash savings.</p></div><button className="primary-button" disabled={!basesReady || !incomeConfirmed || !commitmentsConfirmed || form.groceries === '' || form.restaurants === '' || balance < 0}>{busy ? 'Saving…' : 'Save monthly targets'}</button></div>
    </fieldset>{error && <p role="alert" className="mt-3 text-accent-coral">{error}</p>}{notice && <p role="status" className="mt-3 text-accent-green">{notice}</p>}
  </form>
}
function MoneyInput({ label, value, onChange }) { return <label className="block text-sm text-white/70">{label}<input required type="number" min="0" max="10000000" step="0.01" inputMode="decimal" value={value} onFocus={e => e.target.select()} onChange={e => onChange(e.target.value)} className="field mt-2 block w-full text-lg tabular-nums"/></label> }
