import { useEffect,useState } from 'react'
import { cents,dateKey,dollars,incomeSuggestion,monday,monthlyFromWeekly,previousMonthWeekly,recommendWeekly,shiftDay,weeklyBaselines,weeklyFromMonthly,weeklySummary,WEEKLY_CATEGORIES } from '../lib/weekly.js'
import { formatCurrency } from '../lib/finance.js'
import { postJson } from '../lib/sharedState.js'

const money=value=>formatCurrency(dollars(value),{cents:true})
const labelMonth=key=>new Date(`${key}-01T12:00:00`).toLocaleDateString('en-US',{month:'long',year:'numeric'})
const prettyDate=value=>new Date(`${value}T00:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric'})

export default function WeeklyBudgetV2({month,shared,onChanged,onDirtyChange}){
  const [week,setWeek]=useState(monday(dateKey()))
  const weekly=weeklySummary(shared.transactions||[],shared.budgets||[],week)
  const saved=(shared.savingsSettings||[]).find(row=>row.monthKey===month)
  const targets=WEEKLY_CATEGORIES.map(bucket=>(shared.budgets||[]).find(row=>row.monthKey===month&&row.bucket===bucket)?.target)
  const budget=(shared.budgets||[]).filter(row=>row.monthKey===month).reduce((sum,row)=>sum+cents(row.target),0)
  const extra=saved?Math.max(0,saved.income-saved.savings-budget):0,shortfall=saved?Math.max(0,budget-(saved.income-saved.savings)):0
  return <div className="weekly-workspace">
    <section className="instrument-panel weekly-main-panel"><div className="panel-titlebar weekly-titlebar"><div><div className="eyebrow">Monday–Sunday</div><h1>Your weekly spending</h1><p>{prettyDate(weekly.start)}–{prettyDate(weekly.end)} · fresh allowances, no rollover</p></div><div className="week-controls"><button className="secondary-button" aria-label="Previous week" onClick={()=>setWeek(shiftDay(week,-7))}>←</button><label><span className="sr-only">Week containing</span><input aria-label="Week containing date" type="date" value={week} onChange={event=>event.target.value&&setWeek(monday(event.target.value))} className="field"/></label><button className="secondary-button" aria-label="Next week" onClick={()=>setWeek(shiftDay(week,7))}>→</button><button className="secondary-button" onClick={()=>setWeek(monday(dateKey()))}>This week</button></div></div><div className="weekly-category-list">{weekly.categories.map((category,index)=><WeeklyCategory key={category.bucket} category={category} icon={index?'🍽️':'🥦'}/>)}</div></section>
    <aside className="instrument-panel weekly-plan-summary"><div className="eyebrow">Savings-first plan</div><h2>{labelMonth(month)}</h2><div className="weekly-summary-value"><span>Savings goal</span><strong>{saved?money(saved.savings):'$1,000.00'}</strong></div><div className="weekly-summary-value"><span>Expected income</span><strong>{saved?money(saved.income):'Not confirmed'}</strong></div><div className="weekly-summary-value"><span>{shortfall?'Goal shortfall':'Potential extra savings'}</span><strong className={shortfall?'negative':'positive'}>{saved?money(shortfall||extra):'—'}</strong></div><div className="weekly-target-pair"><div><span>Groceries / week</span><strong>{targets[0]==null?'Not set':money(weeklyFromMonthly(cents(targets[0])))}</strong></div><div><span>Dining / week</span><strong>{targets[1]==null?'Not set':money(weeklyFromMonthly(cents(targets[1])))}</strong></div></div><p>{saved?'The savings goal is reserved before these weekly targets. Extra capacity is potential, not money already transferred.':'Confirm income and the monthly savings goal before relying on recommendations.'}</p></aside>
    <section className="instrument-panel weekly-planner-disclosure weekly-planner-open"><div className="weekly-planner-content"><SavingsPlanner key={month} month={month} shared={shared} onChanged={onChanged} onDirtyChange={onDirtyChange}/></div></section>
  </div>
}

function WeeklyCategory({category,icon}){const percentage=category.allowance==null?0:Math.min(100,Math.max(0,category.spent/category.allowance*100));return <article className="weekly-category-card"><div className="weekly-category-heading"><span aria-hidden="true">{icon}</span><div><h2>{category.bucket}</h2><p>{category.allowance==null?`Missing targets: ${category.missing.join(', ')}`:`${money(category.spent)} spent of ${money(category.allowance)}`}</p></div><div className="weekly-category-remaining"><strong className={category.remaining<0?'negative':''}>{category.allowance==null?'Budget not set':money(Math.abs(category.remaining))}</strong><small>{category.allowance==null?'weekly target needed':category.remaining<0?'over allowance':'remaining'}</small></div></div>{category.allowance!=null&&<div className="weekly-card-progress"><span style={{width:`${percentage}%`}} className={category.remaining<0?'budget-progress-over':''}/></div>}<details className="weekly-purchases"><summary>Purchases <span>{category.transactions.length}</span></summary><ul>{category.transactions.map(row=><li key={row.txnKey}><span>{row.date.slice(5)} · {row.name}{row.source==='manual'&&<em>manual</em>}</span><strong>{formatCurrency(row.amount,{cents:true})}</strong></li>)}{!category.transactions.length&&<li className="empty-row">No recorded purchases yet. Manual entries appear immediately.</li>}</ul></details></article>}

function SavingsPlanner({month,shared,onChanged,onDirtyChange}){
  const saved=(shared.savingsSettings||[]).find(row=>row.monthKey===month)
  const history=weeklyBaselines(shared.transactions||[],shared.importCoverage||[],month<dateKey().slice(0,7)?`${month}-01`:dateKey())
  const previous=previousMonthWeekly(shared.transactions||[],shared.importCoverage||[],month)
  const income=incomeSuggestion(shared.transactions||[],shared.monthlyReviews||[],`${month}-01`,shared.importCoverage||[])
  const targets=WEEKLY_CATEGORIES.map(bucket=>(shared.budgets||[]).find(row=>row.monthKey===month&&row.bucket===bucket)?.target)
  const weeklyBaseline=(index)=>saved?weeklyFromMonthly(saved[index?'restaurantsBaseline':'groceriesBaseline']):history.categories[index].weekly
  const [form,setForm]=useState(()=>({income:saved?dollars(saved.income):income.amount==null?'':dollars(income.amount),savings:saved?dollars(saved.savings):1000,groceriesBaseline:weeklyBaseline(0)==null?'':dollars(weeklyBaseline(0)),restaurantsBaseline:weeklyBaseline(1)==null?'':dollars(weeklyBaseline(1)),groceries:targets[0]==null?'':dollars(weeklyFromMonthly(cents(targets[0]))),restaurants:targets[1]==null?'':dollars(weeklyFromMonthly(cents(targets[1])))}))
  const [incomeConfirmed,setIncomeConfirmed]=useState(Boolean(saved)),[commitmentsConfirmed,setCommitmentsConfirmed]=useState(false),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
  const locked=(shared.monthlyCloseouts||[]).some(row=>row.monthKey===month)
  const other=(shared.budgets||[]).filter(row=>row.monthKey===month&&!WEEKLY_CATEGORIES.includes(row.bucket)).reduce((sum,row)=>sum+cents(row.target),0)
  const recommendation=recommendWeekly({income:cents(form.income),savings:cents(form.savings),other,groceries:cents(form.groceriesBaseline),restaurants:cents(form.restaurantsBaseline)})
  const plannedGroceries=monthlyFromWeekly(cents(form.groceries)),plannedRestaurants=monthlyFromWeekly(cents(form.restaurants)),balance=cents(form.income)-cents(form.savings)-other-plannedGroceries-plannedRestaurants
  const basesReady=form.groceriesBaseline!==''&&form.restaurantsBaseline!==''&&form.income!==''
  useEffect(()=>{onDirtyChange(dirty);return()=>onDirtyChange(false)},[dirty,onDirtyChange])
  useEffect(()=>{if(!dirty)return;const warn=event=>{event.preventDefault();event.returnValue=''};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty])
  const update=(key,value)=>{setForm(current=>({...current,[key]:value}));setDirty(true);setNotice('')}
  const save=async event=>{event.preventDefault();setBusy(true);setError('');setNotice('');try{const result=await postJson('/api/weekly-plan',{monthKey:month,income:cents(form.income),savings:cents(form.savings),groceriesWeekly:cents(form.groceries),restaurantsWeekly:cents(form.restaurants),groceriesBaselineWeekly:cents(form.groceriesBaseline),restaurantsBaselineWeekly:cents(form.restaurantsBaseline),incomeConfirmed,commitmentsConfirmed});setDirty(false);await onChanged();setNotice(result.affordability.shortfall?`Saved with a ${money(result.affordability.shortfall)} savings-goal shortfall. The warning will remain visible.`:'Weekly targets saved. Their monthly category budgets and allowances are updated.')}catch(reason){setError(reason.message)}finally{setBusy(false)}}
  return <form onSubmit={save} className="savings-planner"><div className="planner-intro"><div><div className="eyebrow">Savings first</div><h2>Plan weekly targets for {labelMonth(month)}</h2></div><p>Compare recent spending, protect the monthly savings goal, then choose what groceries and dining should cost each week.</p></div>{locked&&<p className="panel-warning">This month is closed. Reopen it from Overview to change its plan.</p>}<fieldset disabled={locked||busy||!shared.available}>
    <div className="planner-grid"><MoneyInput label="Expected monthly take-home income" value={form.income} onChange={value=>{update('income',value);setIncomeConfirmed(false)}}/><MoneyInput label="Monthly savings goal" value={form.savings} onChange={value=>update('savings',value)}/></div>
    <p className="planner-help">{income.amount==null?'No reviewed income history yet. Enter your expected take-home income.':`Income suggestion: ${money(income.amount)}, averaged from ${income.months.join(', ')}. Confirm it accounts for irregular pay.`}</p>
    <label className="check-row"><input type="checkbox" checked={incomeConfirmed} onChange={event=>setIncomeConfirmed(event.target.checked)}/>I confirm this expected income for {labelMonth(month)}.</label>
    <div className="planner-commitments"><div><span>Other saved category targets</span><strong>{money(other)}</strong></div><label className="check-row"><input type="checkbox" checked={commitmentsConfirmed} onChange={event=>setCommitmentsConfirmed(event.target.checked)}/>These targets include our other bills and commitments, without double-counting savings.</label></div>
    <div className="planner-section"><h3>What recent spending says</h3><p>{history.weeks} fully covered weeks in the trailing 12. {history.weeks<4?'Enter weekly baselines because history is limited.':'The completed-week median drives the recommendation; last month is context.'}</p><div className="weekly-evidence-grid">{WEEKLY_CATEGORIES.map((bucket,index)=><EvidenceCard key={bucket} bucket={bucket} previous={previous.categories[index]} previousComplete={previous.complete} median={history.categories[index].weekly} recommended={recommendation[index?'restaurants':'groceries']} baseline={form[index?'restaurantsBaseline':'groceriesBaseline']} onBaseline={value=>update(index?'restaurantsBaseline':'groceriesBaseline',value)}/>)}</div></div>
    <div className="recommendation-box"><span>Income − savings goal − other targets</span><strong>{form.income===''?'Confirm income to calculate':`${money(recommendation.available)} available per month`}</strong><p>Recommended weekly plan: {basesReady?`${money(recommendation.groceries)} groceries + ${money(recommendation.restaurants)} dining`:'Enter income and both weekly baselines first.'}</p>{basesReady&&recommendation.shortfall>0&&<p role="status" className="panel-warning">To protect savings, the recommendation cuts {money(recommendation.shortfall)} per month from the historical grocery-and-dining baseline.</p>}<button type="button" className="secondary-button" disabled={!basesReady} onClick={()=>{update('groceries',dollars(recommendation.groceries));update('restaurants',dollars(recommendation.restaurants))}}>Use recommended weekly targets</button></div>
    <div className="planner-grid"><MoneyInput label="My grocery weekly target" value={form.groceries} onChange={value=>update('groceries',value)}/><MoneyInput label="My dining weekly target" value={form.restaurants} onChange={value=>update('restaurants',value)}/></div>
    <div className={`planner-save ${balance<0?'planner-save-warning':''}`}><div><strong className={form.income!==''&&balance<0?'negative':'positive'}>{form.income===''?'Enter expected income first':balance<0?`${money(-balance)} savings-goal shortfall`:`${money(balance)} potential additional savings`}</strong><small>{balance<0?'You may save this plan; the tradeoff will remain visible.':'A plan, not a bank transfer or guaranteed cash savings.'}</small></div><button className="primary-button" disabled={!basesReady||!incomeConfirmed||!commitmentsConfirmed||form.groceries===''||form.restaurants===''}>{busy?'Saving…':'Save weekly targets'}</button></div>
  </fieldset>{error&&<p role="alert" className="panel-error">{error}</p>}{notice&&<p role="status" className={balance<0?'panel-warning':'panel-success'}>{notice}</p>}</form>
}

function EvidenceCard({bucket,previous,previousComplete,median,recommended,baseline,onBaseline}){return <article className="weekly-evidence-card"><div><span>{bucket==='Groceries'?'🥦':'🍽️'}</span><strong>{bucket}</strong></div><dl><div><dt>Last month / week</dt><dd>{money(previous.weekly)} <small>{previousComplete?'complete':'partial data'}</small></dd></div><div><dt>12-week median</dt><dd>{median==null?'Needs 4 covered weeks':money(median)}</dd></div><div><dt>Recommended</dt><dd className="positive">{money(recommended)} / week</dd></div></dl><MoneyInput label="Weekly baseline" value={baseline} onChange={onBaseline}/></article>}
function MoneyInput({label,value,onChange}){return <label className="money-input">{label}<input required type="number" min="0" max="10000000" step="0.01" inputMode="decimal" value={value} onFocus={event=>event.target.select()} onChange={event=>onChange(event.target.value)} className="field"/></label>}
